/**
 * HashRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HashRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HashRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HashRepository,
} from "@consentrail/services/evidence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HashRepositoryDdb } from "./hash-repository.ddb.js";

/**
 * HashRepositoryAdapter
 *
 * Implements HashRepository port for infrastructure layer.
 */
export class HashRepositoryAdapter implements HashRepository {
  private readonly ddb: HashRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HashRepositoryDdb(this.dynamoClient);
  }

  async listEvidenceHashes(input: Parameters<HashRepository['listEvidenceHashes']>[0]): Promise<Awaited<ReturnType<HashRepository['listEvidenceHashes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEvidenceHashes(input);
  }

  async registerEvidenceHash(input: Parameters<HashRepository['registerEvidenceHash']>[0]): Promise<Awaited<ReturnType<HashRepository['registerEvidenceHash']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerEvidenceHash(input);
  }

  async getEvidenceHash(input: Parameters<HashRepository['getEvidenceHash']>[0]): Promise<Awaited<ReturnType<HashRepository['getEvidenceHash']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEvidenceHash(input);
  }
}
