/**
 * IntegrityProofRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IntegrityProofRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IntegrityProofRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IntegrityProofRepository,
} from "@consentrail/services/evidence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IntegrityProofRepositoryDdb } from "./integrity-proof-repository.ddb.js";

/**
 * IntegrityProofRepositoryAdapter
 *
 * Implements IntegrityProofRepository port for infrastructure layer.
 */
export class IntegrityProofRepositoryAdapter implements IntegrityProofRepository {
  private readonly ddb: IntegrityProofRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IntegrityProofRepositoryDdb(this.dynamoClient);
  }

  async listIntegrityProofs(input: Parameters<IntegrityProofRepository['listIntegrityProofs']>[0]): Promise<Awaited<ReturnType<IntegrityProofRepository['listIntegrityProofs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listIntegrityProofs(input);
  }

  async issueIntegrityProof(input: Parameters<IntegrityProofRepository['issueIntegrityProof']>[0]): Promise<Awaited<ReturnType<IntegrityProofRepository['issueIntegrityProof']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.issueIntegrityProof(input);
  }

  async getIntegrityProof(input: Parameters<IntegrityProofRepository['getIntegrityProof']>[0]): Promise<Awaited<ReturnType<IntegrityProofRepository['getIntegrityProof']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getIntegrityProof(input);
  }
}
