/**
 * OrphanRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OrphanRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OrphanRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OrphanRepository,
} from "@consentrail/services/evidence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OrphanRepositoryDdb } from "./orphan-repository.ddb.js";

/**
 * OrphanRepositoryAdapter
 *
 * Implements OrphanRepository port for infrastructure layer.
 */
export class OrphanRepositoryAdapter implements OrphanRepository {
  private readonly ddb: OrphanRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OrphanRepositoryDdb(this.dynamoClient);
  }

  async orphanEvidenceHash(input: Parameters<OrphanRepository['orphanEvidenceHash']>[0]): Promise<Awaited<ReturnType<OrphanRepository['orphanEvidenceHash']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.orphanEvidenceHash(input);
  }
}
