/**
 * VerifyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerifyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VerifyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VerifyRepository,
} from "@consentrail/services/evidence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VerifyRepositoryDdb } from "./verify-repository.ddb.js";

/**
 * VerifyRepositoryAdapter
 *
 * Implements VerifyRepository port for infrastructure layer.
 */
export class VerifyRepositoryAdapter implements VerifyRepository {
  private readonly ddb: VerifyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VerifyRepositoryDdb(this.dynamoClient);
  }

  async verifyIntegrityProof(input: Parameters<VerifyRepository['verifyIntegrityProof']>[0]): Promise<Awaited<ReturnType<VerifyRepository['verifyIntegrityProof']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.verifyIntegrityProof(input);
  }
}
