/**
 * ConsortiumRole Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/consortium-roles.openapi.types.js";
import { schemas } from "../schemas/consortium-roles.schemas.js";

/**
 * Entity: ConsortiumRoleEntity
 * Description: Represents the ConsortiumRole domain model.
 * Source: schemas.ConsortiumRole
 * Type: Domain Entity (API)
 */
export const ConsortiumRoleEntitySchema = schemas.ConsortiumRole;
export type ConsortiumRoleEntity = components["schemas"]["ConsortiumRole"];
