/**
 * GoLiveGate Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/consortium-roles.openapi.types.js";
import { schemas } from "../schemas/consortium-roles.schemas.js";

/**
 * Entity: GoLiveGateEntity
 * Description: Represents the GoLiveGate domain model.
 * Source: schemas.GoLiveGate
 * Type: Domain Entity (API)
 */
export const GoLiveGateEntitySchema = schemas.GoLiveGate;
export type GoLiveGateEntity = components["schemas"]["GoLiveGate"];
