/**
 * ListIntegrityProof DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListIntegrityProofsParams } from "@consentrail/core/evidence";

export function createListIntegrityProofRequest(overrides: Partial<ListIntegrityProofsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
