/**
 * ExecuteListOwnerMediationGrants - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListOwnerMediationGrants Use Case
 *
 * DDD: Application use case for list OwnerMediationGrant.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListOwnerMediationGrantsInput, ListOwnerMediationGrantsOutput } from "../dto/owner-mediation-grant.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { OwnerMediationGrantRepository } from "../ports";

export class ExecuteListOwnerMediationGrants {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ownerMediationGrant: OwnerMediationGrantRepository
  ) {}

  async execute(input: ListOwnerMediationGrantsInput): Promise<ListOwnerMediationGrantsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.ownerMediationGrant.listOwnerMediationGrants({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListOwnerMediationGrantsOutput;
  }
}
