/**
 * ExecuteRequestOwnerMediationGrant - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRequestOwnerMediationGrant Use Case
 *
 * DDD: Application use case for get OwnerMediationGrant.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RequestOwnerMediationGrantInput, RequestOwnerMediationGrantOutput } from "../dto/owner-mediation-grant.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { OwnerMediationGrantRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRequestOwnerMediationGrant {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ownerMediationGrant: OwnerMediationGrantRepository
  ) {}

  async execute(input: RequestOwnerMediationGrantInput): Promise<RequestOwnerMediationGrantOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: consentId, expiresAt, requestingMemberId, scope
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).consentId) {
      throw new ValidationError("consentId is required");
    }
    const consentId = (input as any).consentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.ownerMediationGrant.requestOwnerMediationGrant({ consentId: consentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${consentId}`);
    }

    return entity as RequestOwnerMediationGrantOutput;
  }
}
