/**
 * ExecuteWithdrawConsent - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteWithdrawConsent Use Case
 *
 * DDD: Application use case for get Withdraw.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { WithdrawConsentInput, WithdrawConsentOutput } from "../dto/withdraw.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { WithdrawRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteWithdrawConsent {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly withdraw: WithdrawRepository
  ) {}

  async execute(input: WithdrawConsentInput): Promise<WithdrawConsentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).consentId) {
      throw new ValidationError("consentId is required");
    }
    const consentId = (input as any).consentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.withdraw.withdrawConsent({ consentId: consentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${consentId}`);
    }

    return entity as WithdrawConsentOutput;
  }
}
