/**
 * GetProcessingStopState handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getProcessingStopState } from "@consentrail/api-server/domains/consents/handlers";
import type { ConsentsDDDDependencies } from "@consentrail/api-server/domains/consents";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { CONSENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetProcessingStopState", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConsentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConsentsDDDDependencies>(
      CONSENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetProcessingStopState, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { consentId: entity.id };

    await getProcessingStopState(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetProcessingStopState.execute).toHaveBeenCalledWith(expect.objectContaining({ consentId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { consentId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetProcessingStopState, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getProcessingStopState(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
