/**
 * DryRunRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DryRunRepository Port
 *
 * DDD: Application port for dryrunrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DryRunTripleBlindPolicyInput, DryRunTripleBlindPolicyOutput } from "../dto/dry-run.dto";
export interface DryRunRepository {
  dryRunTripleBlindPolicy(input: DryRunTripleBlindPolicyInput): Promise<DryRunTripleBlindPolicyOutput>;
}

export type { DryRunTripleBlindPolicyInput, DryRunTripleBlindPolicyOutput } from "../dto/dry-run.dto";
