/**
 * Models barrel export - All Obligations entities
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./compliance-alert.entity.js";
