/**
 * DisableTripleBlindPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { disableTripleBlindPolicy } from "@consentrail/api-server/domains/triple-blind-exchange/handlers";
import type { TripleBlindExchangeDDDDependencies } from "@consentrail/api-server/domains/triple-blind-exchange";
import { createUpdateDisableRequest } from "@consentrail/factories/triple-blind-exchange";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { TRIPLEBLINDEXCHANGE_USE_CASES } from "../__factories__/use-cases.js";

describe("DisableTripleBlindPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TripleBlindExchangeDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TripleBlindExchangeDDDDependencies>(
      TRIPLEBLINDEXCHANGE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = createUpdateDisableRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { policyId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeDisableTripleBlindPolicy, "execute").mockResolvedValue(useCaseResult);

    await disableTripleBlindPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDisableTripleBlindPolicy.execute).toHaveBeenCalledWith(expect.objectContaining({ policyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
