/**
 * IntegrityProof DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IntegrityProof DTOs
 *
 * DDD: Application DTOs for IntegrityProof use cases.
 */

import type { GetIntegrityProofParams, IssueIntegrityProofRequestInput, ListIntegrityProofsParams } from "@consentrail/core/evidence/types";

export type ListIntegrityProofsInput = ListIntegrityProofsParams;

export type IssueIntegrityProofInput = IssueIntegrityProofRequestInput;

export type GetIntegrityProofInput = GetIntegrityProofParams;

export type ListIntegrityProofsOutput = {};

export type IssueIntegrityProofOutput = {};

export type GetIntegrityProofOutput = {};
