/**
 * Orphan DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Orphan DTOs
 *
 * DDD: Application DTOs for Orphan use cases.
 */

import type { OrphanEvidenceHashParams } from "@consentrail/core/evidence/types";

export type OrphanEvidenceHashInput = OrphanEvidenceHashParams;

export type OrphanEvidenceHashOutput = {};
