/**
 * Repository interface for ConsortiumRole
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ConsortiumRoleEntity
} from "../models/consortium-role.entity.js";
import type {
  ListConsortiumRolesParams,
  ConsortiumRole
} from "../types/index.js";
/**
 * ConsortiumRoleRepository Interface
 */
export interface ConsortiumRoleRepository extends CreateReadRepository<ConsortiumRoleEntity, ConsortiumRole, string, ListConsortiumRolesParams> {

}
