/**
 * DisableRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisableRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DisableRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DisableRepository,
} from "@consentrail/services/triple-blind-exchange";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DisableRepositoryDdb } from "./disable-repository.ddb.js";

/**
 * DisableRepositoryAdapter
 *
 * Implements DisableRepository port for infrastructure layer.
 */
export class DisableRepositoryAdapter implements DisableRepository {
  private readonly ddb: DisableRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DisableRepositoryDdb(this.dynamoClient);
  }

  async disableTripleBlindPolicy(input: Parameters<DisableRepository['disableTripleBlindPolicy']>[0]): Promise<Awaited<ReturnType<DisableRepository['disableTripleBlindPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.disableTripleBlindPolicy(input);
  }
}
