/**
 * EnableRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EnableRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EnableRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EnableRepository,
} from "@consentrail/services/triple-blind-exchange";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EnableRepositoryDdb } from "./enable-repository.ddb.js";

/**
 * EnableRepositoryAdapter
 *
 * Implements EnableRepository port for infrastructure layer.
 */
export class EnableRepositoryAdapter implements EnableRepository {
  private readonly ddb: EnableRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EnableRepositoryDdb(this.dynamoClient);
  }

  async enableTripleBlindPolicy(input: Parameters<EnableRepository['enableTripleBlindPolicy']>[0]): Promise<Awaited<ReturnType<EnableRepository['enableTripleBlindPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.enableTripleBlindPolicy(input);
  }
}
