/**
 * ComplianceAlertRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplianceAlertRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ComplianceAlertRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ComplianceAlertRepository,
} from "@consentrail/services/obligations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ComplianceAlertRepositoryDdb } from "./compliance-alert-repository.ddb.js";

/**
 * ComplianceAlertRepositoryAdapter
 *
 * Implements ComplianceAlertRepository port for infrastructure layer.
 */
export class ComplianceAlertRepositoryAdapter implements ComplianceAlertRepository {
  private readonly ddb: ComplianceAlertRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ComplianceAlertRepositoryDdb(this.dynamoClient);
  }

  async listComplianceAlerts(input: Parameters<ComplianceAlertRepository['listComplianceAlerts']>[0]): Promise<Awaited<ReturnType<ComplianceAlertRepository['listComplianceAlerts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listComplianceAlerts(input);
  }
}
