/**
 * ObligationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ObligationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ObligationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ObligationRepository,
} from "@consentrail/services/obligations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ObligationRepositoryDdb } from "./obligation-repository.ddb.js";

/**
 * ObligationRepositoryAdapter
 *
 * Implements ObligationRepository port for infrastructure layer.
 */
export class ObligationRepositoryAdapter implements ObligationRepository {
  private readonly ddb: ObligationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ObligationRepositoryDdb(this.dynamoClient);
  }

  async listObligationContracts(input: Parameters<ObligationRepository['listObligationContracts']>[0]): Promise<Awaited<ReturnType<ObligationRepository['listObligationContracts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listObligationContracts(input);
  }

  async createObligationContract(input: Parameters<ObligationRepository['createObligationContract']>[0]): Promise<Awaited<ReturnType<ObligationRepository['createObligationContract']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createObligationContract(input);
  }

  async getObligationContract(input: Parameters<ObligationRepository['getObligationContract']>[0]): Promise<Awaited<ReturnType<ObligationRepository['getObligationContract']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getObligationContract(input);
  }
}
