/**
 * WaiveRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WaiveRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements WaiveRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  WaiveRepository,
} from "@consentrail/services/obligations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { WaiveRepositoryDdb } from "./waive-repository.ddb.js";

/**
 * WaiveRepositoryAdapter
 *
 * Implements WaiveRepository port for infrastructure layer.
 */
export class WaiveRepositoryAdapter implements WaiveRepository {
  private readonly ddb: WaiveRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new WaiveRepositoryDdb(this.dynamoClient);
  }

  async waiveComplianceAlert(input: Parameters<WaiveRepository['waiveComplianceAlert']>[0]): Promise<Awaited<ReturnType<WaiveRepository['waiveComplianceAlert']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.waiveComplianceAlert(input);
  }
}
