/**
 * Consent DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Consent DTOs
 *
 * DDD: Application DTOs for Consent use cases.
 */

import type { CaptureConsentRequestInput, GetConsentRecordParams, ListConsentRecordsParams } from "@consentrail/core/consents/types";

export type ListConsentRecordsInput = ListConsentRecordsParams;

export type CaptureConsentInput = CaptureConsentRequestInput;

export type GetConsentRecordInput = GetConsentRecordParams;

export type ListConsentRecordsOutput = {};

export type CaptureConsentOutput = {};

export type GetConsentRecordOutput = {};
