/**
 * OwnerMediationGrant DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OwnerMediationGrant DTOs
 *
 * DDD: Application DTOs for OwnerMediationGrant use cases.
 */

import type { GetOwnerMediationGrantParams, ListOwnerMediationGrantsParams, RequestOwnerMediationGrantRequestInput } from "@consentrail/core/consents/types";

export type ListOwnerMediationGrantsInput = ListOwnerMediationGrantsParams;

export type RequestOwnerMediationGrantInput = RequestOwnerMediationGrantRequestInput;

export type GetOwnerMediationGrantInput = GetOwnerMediationGrantParams;

export type ListOwnerMediationGrantsOutput = {};

export type RequestOwnerMediationGrantOutput = {};

export type GetOwnerMediationGrantOutput = {};
