/**
 * CounselGate Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CounselGateEntity } from "@consentrail/core/counsel-gates/models/index.js";
import { counselGatesSchemas } from "@consentrail/core/counsel-gates";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cng";

export function createCounselGate(overrides: Partial<CounselGateEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cng_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    rightsCaseId: overrides.rightsCaseId ?? faker.string.uuid(),
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return counselGatesSchemas.CounselGate.parse(raw);
}

export function counselGateBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCounselGate(overrides));
}
