/**
 * Enable DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Enable DTOs
 *
 * DDD: Application DTOs for Enable use cases.
 */

import type { EnableTripleBlindPolicyParams } from "@consentrail/core/triple-blind-exchange/types";

export type EnableTripleBlindPolicyInput = EnableTripleBlindPolicyParams;

export type EnableTripleBlindPolicyOutput = {};
