/**
 * RegulatorView Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/regulator-views.openapi.types.js";
import { schemas } from "../schemas/regulator-views.schemas.js";

/**
 * Entity: RegulatorViewEntity
 * Description: Represents the RegulatorView domain model.
 * Source: schemas.RegulatorView
 * Type: Domain Entity (API)
 */
export const RegulatorViewEntitySchema = schemas.RegulatorView;
export type RegulatorViewEntity = components["schemas"]["RegulatorView"];
