/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the consents domain.
 * Use these factories in tests to create test data.
 */

export { createCreateApproveRequest } from "./approve/dto/create-approve.dto.factory.js";
export { createCreateDenyRequest } from "./deny/dto/create-deny.dto.factory.js";
export { createCreateProcessingStopRequest } from "./processing-stop/dto/create-processing-stop.dto.factory.js";
export { createCreateWithdrawRequest } from "./withdraw/dto/create-withdraw.dto.factory.js";
export { createOwnerMediationGrant } from "./owner-mediation-grant/entity/owner-mediation-grant.entity.factory.js";
