/**
 * ExecuteRecordSecurityEvent - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordSecurityEvent Use Case
 *
 * DDD: Application use case for get SecurityEvent.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordSecurityEventInput, RecordSecurityEventOutput } from "../dto/security-event.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { SecurityEventRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordSecurityEvent {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly securityEvent: SecurityEventRepository
  ) {}

  async execute(input: RecordSecurityEventInput): Promise<RecordSecurityEventOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.secId();

    // All field names extracted from OpenAPI spec: appId, detail, kind, participantId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).appId) {
      throw new ValidationError("appId is required");
    }
    const appId = (input as any).appId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.securityEvent.recordSecurityEvent({ appId: appId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${appId}`);
    }

    return entity as RecordSecurityEventOutput;
  }
}
