/**
 * GoLiveGate Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { GoLiveGateEntity } from "@consentrail/core/consortium-roles/models/index.js";
import { consortiumRolesSchemas } from "@consentrail/core/consortium-roles";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cnr";

export function createGoLiveGate(overrides: Partial<GoLiveGateEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    missing: overrides.missing ?? [],
    ready: overrides.ready ?? faker.datatype.boolean(),
    ...overrides,
  };

  return consortiumRolesSchemas.GoLiveGate.parse(raw);
}

export function goLiveGateBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createGoLiveGate(overrides));
}
