/**
 * DryRunTripleBlindPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { dryRunTripleBlindPolicy } from "@consentrail/api-server/domains/triple-blind-exchange/handlers";
import type { TripleBlindExchangeDDDDependencies } from "@consentrail/api-server/domains/triple-blind-exchange";
import { createCreateDryRunRequest } from "@consentrail/factories/triple-blind-exchange";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { TRIPLEBLINDEXCHANGE_USE_CASES } from "../__factories__/use-cases.js";

describe("DryRunTripleBlindPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TripleBlindExchangeDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TripleBlindExchangeDDDDependencies>(
      TRIPLEBLINDEXCHANGE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateDryRunRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeDryRunTripleBlindPolicy, "execute").mockResolvedValue(useCaseResult);

    await dryRunTripleBlindPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDryRunTripleBlindPolicy.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
