/**
 * HandToCounselRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HandToCounselRepository Port
 *
 * DDD: Application port for handtocounselrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { HandRightsCaseToCounselInput, HandRightsCaseToCounselOutput } from "../dto/hand-to-counsel.dto";
export interface HandToCounselRepository {
  handRightsCaseToCounsel(input: HandRightsCaseToCounselInput): Promise<HandRightsCaseToCounselOutput>;
}

export type { HandRightsCaseToCounselInput, HandRightsCaseToCounselOutput } from "../dto/hand-to-counsel.dto";
