/**
 * Close DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Close DTOs
 *
 * DDD: Application DTOs for Close use cases.
 */

import type { CloseRightsCaseParams, CloseRightsCaseRequestInput } from "@consentrail/core/rights/types";

export type CloseRightsCaseInput = CloseRightsCaseParams & CloseRightsCaseRequestInput;

export type CloseRightsCaseOutput = {};
