/**
 * HandToCounsel DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HandToCounsel DTOs
 *
 * DDD: Application DTOs for HandToCounsel use cases.
 */

import type { HandRightsCaseToCounselParams } from "@consentrail/core/rights/types";

export type HandRightsCaseToCounselInput = HandRightsCaseToCounselParams;

export type HandRightsCaseToCounselOutput = {};
