/**
 * RightsCase DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RightsCase DTOs
 *
 * DDD: Application DTOs for RightsCase use cases.
 */

import type { GetRightsCaseParams, ListRightsCasesParams, OpenRightsCaseRequestInput } from "@consentrail/core/rights/types";

export type ListRightsCasesInput = ListRightsCasesParams;

export type OpenRightsCaseInput = OpenRightsCaseRequestInput;

export type GetRightsCaseInput = GetRightsCaseParams;

export type ListRightsCasesOutput = {};

export type OpenRightsCaseOutput = {};

export type GetRightsCaseOutput = {};
