/**
 * TripleBlindExchange DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TripleBlindExchange Domain Module - Composition root
 *
 * DDD: Composition root for triple-blind-exchange domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DisableRepositoryAdapter,
  DryRunRepositoryAdapter,
  EnableRepositoryAdapter,
  TripleBlindPolicyRepositoryAdapter,
} from "@consentrail/adapters/triple-blind-exchange";
import { getIdGeneratorService } from "@consentrail/adapters";
import type { AdapterDynamoDBClient } from "@consentrail/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateTripleBlindPolicy,
  ExecuteDisableTripleBlindPolicy,
  ExecuteDryRunTripleBlindPolicy,
  ExecuteEnableTripleBlindPolicy,
  ExecuteGetTripleBlindPolicy,
  ExecuteListTripleBlindPolicies,
} from "@consentrail/services/triple-blind-exchange/usecases";
// Ports (interfaces)
import type {
  DisableRepository,
  DryRunRepository,
  EnableRepository,
  TripleBlindPolicyRepository,
} from "@consentrail/services/triple-blind-exchange/ports";

export interface TripleBlindExchangeDomainModule {
  repos: {
    disables: DisableRepository;
    dryRuns: DryRunRepository;
    enables: EnableRepository;
    tripleBlindPolicies: TripleBlindPolicyRepository;
  };
  useCases: {
    disables: {
      update: ExecuteDisableTripleBlindPolicy;
    };
    dryRuns: {
      get: ExecuteDryRunTripleBlindPolicy;
    };
    enables: {
      update: ExecuteEnableTripleBlindPolicy;
    };
    tripleBlindPolicies: {
      create: ExecuteCreateTripleBlindPolicy;
      get: ExecuteGetTripleBlindPolicy;
      list: ExecuteListTripleBlindPolicies;
    };
  };
}

export function buildTripleBlindExchangeDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TripleBlindExchangeDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      disables?: DisableRepository;
      dryRuns?: DryRunRepository;
      enables?: EnableRepository;
      tripleBlindPolicies?: TripleBlindPolicyRepository;
    } = {};

    obj.disables = new DisableRepositoryAdapter(dynamoClient);
    obj.dryRuns = new DryRunRepositoryAdapter(dynamoClient);
    obj.enables = new EnableRepositoryAdapter(dynamoClient);
    obj.tripleBlindPolicies = new TripleBlindPolicyRepositoryAdapter(dynamoClient);
    return {
      disables: obj.disables!,
      dryRuns: obj.dryRuns!,
      enables: obj.enables!,
      tripleBlindPolicies: obj.tripleBlindPolicies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    disables: {
      update: new ExecuteDisableTripleBlindPolicy(executionContext, idGenerator, repos.disables),
    },
    dryRuns: {
      get: new ExecuteDryRunTripleBlindPolicy(executionContext, idGenerator, repos.dryRuns),
    },
    enables: {
      update: new ExecuteEnableTripleBlindPolicy(executionContext, idGenerator, repos.enables),
    },
    tripleBlindPolicies: {
      create: new ExecuteCreateTripleBlindPolicy(executionContext, idGenerator, repos.tripleBlindPolicies),
      get: new ExecuteGetTripleBlindPolicy(executionContext, idGenerator, repos.tripleBlindPolicies),
      list: new ExecuteListTripleBlindPolicies(executionContext, idGenerator, repos.tripleBlindPolicies),
    },
  };
  return { repos, useCases: useCases as TripleBlindExchangeDomainModule["useCases"] };
}
