/**
 * GetTripleBlindPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getTripleBlindPolicy } from "@consentrail/api-server/domains/triple-blind-exchange/handlers";
import type { TripleBlindExchangeDDDDependencies } from "@consentrail/api-server/domains/triple-blind-exchange";
import { createTripleBlindPolicy as createTripleBlindPolicyEntity } from "@consentrail/factories/triple-blind-exchange";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { TRIPLEBLINDEXCHANGE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetTripleBlindPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TripleBlindExchangeDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TripleBlindExchangeDDDDependencies>(
      TRIPLEBLINDEXCHANGE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createTripleBlindPolicyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetTripleBlindPolicy, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { policyId: entity.id };

    await getTripleBlindPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetTripleBlindPolicy.execute).toHaveBeenCalledWith(expect.objectContaining({ policyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { policyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetTripleBlindPolicy, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getTripleBlindPolicy(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
