/**
 * Handlers for CounselGate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CounselGatesDomainModule } from "../dependencies/counsel-gates-ddd.dependencies.js";
import type { GetCounselGateInput, ListCounselGatesInput, OpenCounselGateInput } from "@consentrail/services/counsel-gates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/counsel-gates
 * Operation: listCounselGates
 */
export async function listCounselGates(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CounselGatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCounselGatesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.counselGates.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/counsel-gates
 * Operation: openCounselGate
 */
export async function openCounselGate(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CounselGatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenCounselGateInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.counselGates.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/counsel-gates/{gateId}
 * Operation: getCounselGate
 */
export async function getCounselGate(
  request: FastifyRequest<{ Params: { gateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CounselGatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCounselGateInput = {
    gateId: request.params.gateId,
  };
  const result = await deps.useCases.counselGates.get.execute(input);
  return reply.code(200).send(result);
}


