/**
 * AssignConsortiumRole handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { assignConsortiumRole } from "@consentrail/api-server/domains/consortium-roles/handlers";
import type { ConsortiumRolesDDDDependencies } from "@consentrail/api-server/domains/consortium-roles";
import { createConsortiumRole as createConsortiumRoleEntity } from "@consentrail/factories/consortium-roles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { CONSORTIUMROLES_USE_CASES } from "../__factories__/use-cases.js";

describe("AssignConsortiumRole", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConsortiumRolesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConsortiumRolesDDDDependencies>(
      CONSORTIUMROLES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createConsortiumRoleEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAssignConsortiumRole, "execute").mockResolvedValue(useCaseResult);

    await assignConsortiumRole(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAssignConsortiumRole.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
