/**
 * GetConsortiumRole handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getConsortiumRole } from "@consentrail/api-server/domains/consortium-roles/handlers";
import type { ConsortiumRolesDDDDependencies } from "@consentrail/api-server/domains/consortium-roles";
import { createConsortiumRole as createConsortiumRoleEntity } from "@consentrail/factories/consortium-roles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { CONSORTIUMROLES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetConsortiumRole", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConsortiumRolesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConsortiumRolesDDDDependencies>(
      CONSORTIUMROLES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createConsortiumRoleEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetConsortiumRole, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { roleId: entity.id };

    await getConsortiumRole(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetConsortiumRole.execute).toHaveBeenCalledWith(expect.objectContaining({ roleId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { roleId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetConsortiumRole, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getConsortiumRole(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
