/**
 * ListConsortiumRoles handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listConsortiumRoles } from "@consentrail/api-server/domains/consortium-roles/handlers";
import type { ConsortiumRolesDDDDependencies } from "@consentrail/api-server/domains/consortium-roles";
import { createConsortiumRole as createConsortiumRoleEntity } from "@consentrail/factories/consortium-roles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { CONSORTIUMROLES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListConsortiumRoles", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConsortiumRolesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConsortiumRolesDDDDependencies>(
      CONSORTIUMROLES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createConsortiumRoleEntity({ orgId }),
      createConsortiumRoleEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListConsortiumRoles, "execute").mockResolvedValue(useCaseResult);

    await listConsortiumRoles(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListConsortiumRoles.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
