/**
 * Repository interface for SecurityEvent
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SecurityEventEntity
} from "../models/security-event.entity.js";
import type {
  ListSecurityEventsParams,
  SecurityEvent
} from "../types/index.js";
/**
 * SecurityEventRepository Interface
 */
export interface SecurityEventRepository extends CreateReadRepository<SecurityEventEntity, SecurityEvent, string, ListSecurityEventsParams> {

}
