/**
 * ConsentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConsentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConsentRepository,
} from "@consentrail/services/consents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConsentRepositoryDdb } from "./consent-repository.ddb.js";

/**
 * ConsentRepositoryAdapter
 *
 * Implements ConsentRepository port for infrastructure layer.
 */
export class ConsentRepositoryAdapter implements ConsentRepository {
  private readonly ddb: ConsentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConsentRepositoryDdb(this.dynamoClient);
  }

  async listConsentRecords(input: Parameters<ConsentRepository['listConsentRecords']>[0]): Promise<Awaited<ReturnType<ConsentRepository['listConsentRecords']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConsentRecords(input);
  }

  async captureConsent(input: Parameters<ConsentRepository['captureConsent']>[0]): Promise<Awaited<ReturnType<ConsentRepository['captureConsent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.captureConsent(input);
  }

  async getConsentRecord(input: Parameters<ConsentRepository['getConsentRecord']>[0]): Promise<Awaited<ReturnType<ConsentRepository['getConsentRecord']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getConsentRecord(input);
  }
}
