/**
 * DenyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DenyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DenyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DenyRepository,
} from "@consentrail/services/consents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DenyRepositoryDdb } from "./deny-repository.ddb.js";

/**
 * DenyRepositoryAdapter
 *
 * Implements DenyRepository port for infrastructure layer.
 */
export class DenyRepositoryAdapter implements DenyRepository {
  private readonly ddb: DenyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DenyRepositoryDdb(this.dynamoClient);
  }

  async denyOwnerMediationGrant(input: Parameters<DenyRepository['denyOwnerMediationGrant']>[0]): Promise<Awaited<ReturnType<DenyRepository['denyOwnerMediationGrant']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.denyOwnerMediationGrant(input);
  }
}
