/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve-repository.ddb.js";
export * from "./consent-repository.ddb.js";
export * from "./deny-repository.ddb.js";
export * from "./owner-mediation-grant-repository.ddb.js";
export * from "./processing-stop-repository.ddb.js";
export * from "./withdraw-repository.ddb.js";
export * from "./approve-repository.adapter.js";
export * from "./consent-repository.adapter.js";
export * from "./deny-repository.adapter.js";
export * from "./owner-mediation-grant-repository.adapter.js";
export * from "./processing-stop-repository.adapter.js";
export * from "./withdraw-repository.adapter.js";
