/**
 * OwnerMediationGrantRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OwnerMediationGrantRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OwnerMediationGrantRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OwnerMediationGrantRepository,
} from "@consentrail/services/consents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OwnerMediationGrantRepositoryDdb } from "./owner-mediation-grant-repository.ddb.js";

/**
 * OwnerMediationGrantRepositoryAdapter
 *
 * Implements OwnerMediationGrantRepository port for infrastructure layer.
 */
export class OwnerMediationGrantRepositoryAdapter implements OwnerMediationGrantRepository {
  private readonly ddb: OwnerMediationGrantRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OwnerMediationGrantRepositoryDdb(this.dynamoClient);
  }

  async listOwnerMediationGrants(input: Parameters<OwnerMediationGrantRepository['listOwnerMediationGrants']>[0]): Promise<Awaited<ReturnType<OwnerMediationGrantRepository['listOwnerMediationGrants']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listOwnerMediationGrants(input);
  }

  async requestOwnerMediationGrant(input: Parameters<OwnerMediationGrantRepository['requestOwnerMediationGrant']>[0]): Promise<Awaited<ReturnType<OwnerMediationGrantRepository['requestOwnerMediationGrant']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestOwnerMediationGrant(input);
  }

  async getOwnerMediationGrant(input: Parameters<OwnerMediationGrantRepository['getOwnerMediationGrant']>[0]): Promise<Awaited<ReturnType<OwnerMediationGrantRepository['getOwnerMediationGrant']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getOwnerMediationGrant(input);
  }
}
