/**
 * ProcessingStopRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProcessingStopRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProcessingStopRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProcessingStopRepository,
} from "@consentrail/services/consents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProcessingStopRepositoryDdb } from "./processing-stop-repository.ddb.js";

/**
 * ProcessingStopRepositoryAdapter
 *
 * Implements ProcessingStopRepository port for infrastructure layer.
 */
export class ProcessingStopRepositoryAdapter implements ProcessingStopRepository {
  private readonly ddb: ProcessingStopRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProcessingStopRepositoryDdb(this.dynamoClient);
  }

  async getProcessingStopState(input: Parameters<ProcessingStopRepository['getProcessingStopState']>[0]): Promise<Awaited<ReturnType<ProcessingStopRepository['getProcessingStopState']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getProcessingStopState(input);
  }

  async retryProcessingStopPush(input: Parameters<ProcessingStopRepository['retryProcessingStopPush']>[0]): Promise<Awaited<ReturnType<ProcessingStopRepository['retryProcessingStopPush']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.retryProcessingStopPush(input);
  }
}
