/**
 * OwnerMediationGrant Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/consents.openapi.types.js";
import { schemas } from "../schemas/consents.schemas.js";

/**
 * Entity: OwnerMediationGrantEntity
 * Description: Represents the OwnerMediationGrant domain model.
 * Source: schemas.OwnerMediationGrant
 * Type: Domain Entity (API)
 */
export const OwnerMediationGrantEntitySchema = schemas.OwnerMediationGrant;
export type OwnerMediationGrantEntity = components["schemas"]["OwnerMediationGrant"];
