/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as consentsRoutes from "../../domains/consents/routes/index.js";
import * as consortiumRolesRoutes from "../../domains/consortium-roles/routes/index.js";
import * as counselGatesRoutes from "../../domains/counsel-gates/routes/index.js";
import * as evidenceRoutes from "../../domains/evidence/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as obligationsRoutes from "../../domains/obligations/routes/index.js";
import * as regulatorViewsRoutes from "../../domains/regulator-views/routes/index.js";
import * as rightsRoutes from "../../domains/rights/routes/index.js";
import * as securityEventsRoutes from "../../domains/security-events/routes/index.js";
import * as tripleBlindExchangeRoutes from "../../domains/triple-blind-exchange/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "consents", mod: consentsRoutes },
  { domain: "consortium-roles", mod: consortiumRolesRoutes },
  { domain: "counsel-gates", mod: counselGatesRoutes },
  { domain: "evidence", mod: evidenceRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: [
      "authRoutes",
      "signupRoutes",
      "sessionRoutes",
      "tokenRoutes",
      "profileRoutes",
    ],
  },
  { domain: "obligations", mod: obligationsRoutes },
  { domain: "regulator-views", mod: regulatorViewsRoutes },
  { domain: "rights", mod: rightsRoutes },
  { domain: "security-events", mod: securityEventsRoutes },
  { domain: "triple-blind-exchange", mod: tripleBlindExchangeRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
