/**
 * HandToCounselRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HandToCounselRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HandToCounselRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HandToCounselRepository,
} from "@consentrail/services/rights";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HandToCounselRepositoryDdb } from "./hand-to-counsel-repository.ddb.js";

/**
 * HandToCounselRepositoryAdapter
 *
 * Implements HandToCounselRepository port for infrastructure layer.
 */
export class HandToCounselRepositoryAdapter implements HandToCounselRepository {
  private readonly ddb: HandToCounselRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HandToCounselRepositoryDdb(this.dynamoClient);
  }

  async handRightsCaseToCounsel(input: Parameters<HandToCounselRepository['handRightsCaseToCounsel']>[0]): Promise<Awaited<ReturnType<HandToCounselRepository['handRightsCaseToCounsel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.handRightsCaseToCounsel(input);
  }
}
