/**
 * Obligations DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Obligations Domain Module - Composition root
 *
 * DDD: Composition root for obligations domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcknowledgeRepositoryAdapter,
  ComplianceAlertRepositoryAdapter,
  EvaluateRepositoryAdapter,
  ObligationRepositoryAdapter,
  WaiveRepositoryAdapter,
} from "@consentrail/adapters/obligations";
import { getIdGeneratorService } from "@consentrail/adapters";
import type { AdapterDynamoDBClient } from "@consentrail/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcknowledgeComplianceAlert,
  ExecuteCreateObligationContract,
  ExecuteEvaluateObligationContract,
  ExecuteGetObligationContract,
  ExecuteListComplianceAlerts,
  ExecuteListObligationContracts,
  ExecuteWaiveComplianceAlert,
} from "@consentrail/services/obligations/usecases";
// Ports (interfaces)
import type {
  AcknowledgeRepository,
  ComplianceAlertRepository,
  EvaluateRepository,
  ObligationRepository,
  WaiveRepository,
} from "@consentrail/services/obligations/ports";

export interface ObligationsDomainModule {
  repos: {
    acknowledges: AcknowledgeRepository;
    complianceAlerts: ComplianceAlertRepository;
    evaluates: EvaluateRepository;
    obligations: ObligationRepository;
    waives: WaiveRepository;
  };
  useCases: {
    acknowledges: {
      get: ExecuteAcknowledgeComplianceAlert;
    };
    complianceAlerts: {
      list: ExecuteListComplianceAlerts;
    };
    evaluates: {
      create: ExecuteEvaluateObligationContract;
    };
    obligations: {
      create: ExecuteCreateObligationContract;
      get: ExecuteGetObligationContract;
      list: ExecuteListObligationContracts;
    };
    waives: {
      get: ExecuteWaiveComplianceAlert;
    };
  };
}

export function buildObligationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ObligationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acknowledges?: AcknowledgeRepository;
      complianceAlerts?: ComplianceAlertRepository;
      evaluates?: EvaluateRepository;
      obligations?: ObligationRepository;
      waives?: WaiveRepository;
    } = {};

    obj.acknowledges = new AcknowledgeRepositoryAdapter(dynamoClient);
    obj.complianceAlerts = new ComplianceAlertRepositoryAdapter(dynamoClient);
    obj.evaluates = new EvaluateRepositoryAdapter(dynamoClient);
    obj.obligations = new ObligationRepositoryAdapter(dynamoClient);
    obj.waives = new WaiveRepositoryAdapter(dynamoClient);
    return {
      acknowledges: obj.acknowledges!,
      complianceAlerts: obj.complianceAlerts!,
      evaluates: obj.evaluates!,
      obligations: obj.obligations!,
      waives: obj.waives!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acknowledges: {
      get: new ExecuteAcknowledgeComplianceAlert(executionContext, idGenerator, repos.acknowledges),
    },
    complianceAlerts: {
      list: new ExecuteListComplianceAlerts(executionContext, idGenerator, repos.complianceAlerts),
    },
    evaluates: {
      create: new ExecuteEvaluateObligationContract(executionContext, idGenerator, repos.evaluates),
    },
    obligations: {
      create: new ExecuteCreateObligationContract(executionContext, idGenerator, repos.obligations),
      get: new ExecuteGetObligationContract(executionContext, idGenerator, repos.obligations),
      list: new ExecuteListObligationContracts(executionContext, idGenerator, repos.obligations),
    },
    waives: {
      get: new ExecuteWaiveComplianceAlert(executionContext, idGenerator, repos.waives),
    },
  };
  return { repos, useCases: useCases as ObligationsDomainModule["useCases"] };
}
