/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { complianceAlertRoutes } from "./compliance-alert.routes.js";
export { acknowledgeRoutes } from "./acknowledge.routes.js";
export { evaluateRoutes } from "./evaluate.routes.js";
export { obligationRoutes } from "./obligation.routes.js";
export { waiveRoutes } from "./waive.routes.js";
