/**
 * HandRightsCaseToCounsel handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { handRightsCaseToCounsel } from "@consentrail/api-server/domains/rights/handlers";
import type { RightsDDDDependencies } from "@consentrail/api-server/domains/rights";
import { createCreateHandToCounselRequest } from "@consentrail/factories/rights";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { RIGHTS_USE_CASES } from "../__factories__/use-cases.js";

describe("HandRightsCaseToCounsel", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RightsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RightsDDDDependencies>(
      RIGHTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateHandToCounselRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeHandRightsCaseToCounsel, "execute").mockResolvedValue(useCaseResult);

    await handRightsCaseToCounsel(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeHandRightsCaseToCounsel.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
