/**
 * Routes for SecurityEvent
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSecurityEvent, listSecurityEvents, recordSecurityEvent } from "../handlers/security-event.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function securityEventRoutes(fastify: FastifyInstance) {
  // GET /v1/security-events (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/security-events",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSecurityEventsDependenciesForRequest();
        await listSecurityEvents(request, reply, deps);
      });
    }
  );


  // POST /v1/security-events (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/security-events",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSecurityEventsDependenciesForRequest();
        await recordSecurityEvent(request, reply, deps);
      });
    }
  );


  // GET /v1/security-events/{eventId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/security-events/:eventId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { eventId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSecurityEventsDependenciesForRequest();
        await getSecurityEvent(request, reply, deps);
      });
    }
  );


}
