/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the consortium-roles domain.
 * Use these factories in tests to create test data.
 */

export { createConsortiumRole } from "./consortium-role/entity/consortium-role.entity.factory.js";
export { createCreateAttestRequest } from "./attest/dto/create-attest.dto.factory.js";
export { createGoLiveGate } from "./go-live-gate/entity/go-live-gate.entity.factory.js";
