/**
 * CounselGate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CounselGate DTOs
 *
 * DDD: Application DTOs for CounselGate use cases.
 */

import type { GetCounselGateParams, ListCounselGatesParams, OpenCounselGateRequestInput } from "@consentrail/core/counsel-gates/types";

export type ListCounselGatesInput = ListCounselGatesParams;

export type OpenCounselGateInput = OpenCounselGateRequestInput;

export type GetCounselGateInput = GetCounselGateParams;

export type ListCounselGatesOutput = {};

export type OpenCounselGateOutput = {};

export type GetCounselGateOutput = {};
