/**
 * Routes for RegulatorView
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getRegulatorView, grantRegulatorView, listRegulatorViews } from "../handlers/regulator-view.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function regulatorViewRoutes(fastify: FastifyInstance) {
  // POST /v1/regulator-views (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/regulator-views",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRegulatorViewsDependenciesForRequest();
        await grantRegulatorView(request, reply, deps);
      });
    }
  );


  // GET /v1/regulator-views (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/regulator-views",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRegulatorViewsDependenciesForRequest();
        await listRegulatorViews(request, reply, deps);
      });
    }
  );


  // GET /v1/regulator-views/{viewId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/regulator-views/:viewId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { viewId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRegulatorViewsDependenciesForRequest();
        await getRegulatorView(request, reply, deps);
      });
    }
  );


}
