/**
 * GetRegulatorView handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRegulatorView } from "@consentrail/api-server/domains/regulator-views/handlers";
import type { RegulatorViewsDDDDependencies } from "@consentrail/api-server/domains/regulator-views";
import { createRegulatorView as createRegulatorViewEntity } from "@consentrail/factories/regulator-views";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { REGULATORVIEWS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRegulatorView", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RegulatorViewsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RegulatorViewsDDDDependencies>(
      REGULATORVIEWS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createRegulatorViewEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRegulatorView, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { viewId: entity.id };

    await getRegulatorView(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRegulatorView.execute).toHaveBeenCalledWith(expect.objectContaining({ viewId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { viewId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetRegulatorView, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getRegulatorView(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
