/**
 * ListRegulatorViews handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listRegulatorViews } from "@consentrail/api-server/domains/regulator-views/handlers";
import type { RegulatorViewsDDDDependencies } from "@consentrail/api-server/domains/regulator-views";
import { createRegulatorView as createRegulatorViewEntity } from "@consentrail/factories/regulator-views";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { REGULATORVIEWS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListRegulatorViews", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RegulatorViewsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RegulatorViewsDDDDependencies>(
      REGULATORVIEWS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createRegulatorViewEntity({ orgId }),
      createRegulatorViewEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListRegulatorViews, "execute").mockResolvedValue(useCaseResult);

    await listRegulatorViews(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListRegulatorViews.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
