/**
 * Routes for OwnerMediationGrant
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getOwnerMediationGrant, listOwnerMediationGrants, requestOwnerMediationGrant } from "../handlers/owner-mediation-grant.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function ownerMediationGrantRoutes(fastify: FastifyInstance) {
  // GET /v1/owner-mediation-grants (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/owner-mediation-grants",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await listOwnerMediationGrants(request, reply, deps);
      });
    }
  );


  // POST /v1/owner-mediation-grants (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/owner-mediation-grants",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await requestOwnerMediationGrant(request, reply, deps);
      });
    }
  );


  // GET /v1/owner-mediation-grants/{grantId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/owner-mediation-grants/:grantId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { grantId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await getOwnerMediationGrant(request, reply, deps);
      });
    }
  );


}
