/**
 * Routes for ProcessingStop
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getProcessingStopState, retryProcessingStopPush } from "../handlers/processing-stop.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function processingStopRoutes(fastify: FastifyInstance) {
  // GET /v1/consents/{consentId}/processing-stop (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/consents/:consentId/processing-stop",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { consentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await getProcessingStopState(request, reply, deps);
      });
    }
  );


  // POST /v1/consents/{consentId}/processing-stop (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/consents/:consentId/processing-stop",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { consentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await retryProcessingStopPush(request, reply, deps);
      });
    }
  );


}
