/**
 * ExecuteRevokeRegulatorView - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRevokeRegulatorView Use Case
 *
 * DDD: Application use case for get Revoke.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RevokeRegulatorViewInput, RevokeRegulatorViewOutput } from "../dto/revoke.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { RevokeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRevokeRegulatorView {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly revoke: RevokeRepository
  ) {}

  async execute(input: RevokeRegulatorViewInput): Promise<RevokeRegulatorViewOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rgvId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).viewId) {
      throw new ValidationError("viewId is required");
    }
    const viewId = (input as any).viewId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.revoke.revokeRegulatorView({ viewId: viewId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${viewId}`);
    }

    return entity as RevokeRegulatorViewOutput;
  }
}
