/**
 * Handlers for ConsortiumRole
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConsortiumRolesDomainModule } from "../dependencies/consortium-roles-ddd.dependencies.js";
import type { AssignConsortiumRoleInput, GetConsortiumRoleInput, ListConsortiumRolesInput } from "@consentrail/services/consortium-roles";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/consortium-roles
 * Operation: listConsortiumRoles
 */
export async function listConsortiumRoles(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ConsortiumRolesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListConsortiumRolesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.consortiumRoles.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/consortium-roles
 * Operation: assignConsortiumRole
 */
export async function assignConsortiumRole(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ConsortiumRolesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AssignConsortiumRoleInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.consortiumRoles.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/consortium-roles/{roleId}
 * Operation: getConsortiumRole
 */
export async function getConsortiumRole(
  request: FastifyRequest<{ Params: { roleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ConsortiumRolesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetConsortiumRoleInput = {
    roleId: request.params.roleId,
  };
  const result = await deps.useCases.consortiumRoles.get.execute(input);
  return reply.code(200).send(result);
}


