/**
 * CounselGateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CounselGateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CounselGateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CounselGateRepository,
} from "@consentrail/services/counsel-gates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CounselGateRepositoryDdb } from "./counsel-gate-repository.ddb.js";

/**
 * CounselGateRepositoryAdapter
 *
 * Implements CounselGateRepository port for infrastructure layer.
 */
export class CounselGateRepositoryAdapter implements CounselGateRepository {
  private readonly ddb: CounselGateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CounselGateRepositoryDdb(this.dynamoClient);
  }

  async listCounselGates(input: Parameters<CounselGateRepository['listCounselGates']>[0]): Promise<Awaited<ReturnType<CounselGateRepository['listCounselGates']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCounselGates(input);
  }

  async openCounselGate(input: Parameters<CounselGateRepository['openCounselGate']>[0]): Promise<Awaited<ReturnType<CounselGateRepository['openCounselGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openCounselGate(input);
  }

  async getCounselGate(input: Parameters<CounselGateRepository['getCounselGate']>[0]): Promise<Awaited<ReturnType<CounselGateRepository['getCounselGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCounselGate(input);
  }
}
