/**
 * CounselGates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CounselGates Domain Module - Composition root
 *
 * DDD: Composition root for counsel-gates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CounselGateRepositoryAdapter,
  DecideRepositoryAdapter,
} from "@consentrail/adapters/counsel-gates";
import { getIdGeneratorService } from "@consentrail/adapters";
import type { AdapterDynamoDBClient } from "@consentrail/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDecideCounselGate,
  ExecuteGetCounselGate,
  ExecuteListCounselGates,
  ExecuteOpenCounselGate,
} from "@consentrail/services/counsel-gates/usecases";
// Ports (interfaces)
import type {
  CounselGateRepository,
  DecideRepository,
} from "@consentrail/services/counsel-gates/ports";

export interface CounselGatesDomainModule {
  repos: {
    counselGates: CounselGateRepository;
    decides: DecideRepository;
  };
  useCases: {
    counselGates: {
      create: ExecuteOpenCounselGate;
      get: ExecuteGetCounselGate;
      list: ExecuteListCounselGates;
    };
    decides: {
      get: ExecuteDecideCounselGate;
    };
  };
}

export function buildCounselGatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CounselGatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      counselGates?: CounselGateRepository;
      decides?: DecideRepository;
    } = {};

    obj.counselGates = new CounselGateRepositoryAdapter(dynamoClient);
    obj.decides = new DecideRepositoryAdapter(dynamoClient);
    return {
      counselGates: obj.counselGates!,
      decides: obj.decides!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    counselGates: {
      create: new ExecuteOpenCounselGate(executionContext, idGenerator, repos.counselGates),
      get: new ExecuteGetCounselGate(executionContext, idGenerator, repos.counselGates),
      list: new ExecuteListCounselGates(executionContext, idGenerator, repos.counselGates),
    },
    decides: {
      get: new ExecuteDecideCounselGate(executionContext, idGenerator, repos.decides),
    },
  };
  return { repos, useCases: useCases as CounselGatesDomainModule["useCases"] };
}
