/**
 * RightsCase Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RightsCaseEntity } from "@consentrail/core/rights/models/index.js";
import { rightsSchemas } from "@consentrail/core/rights";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rgt";

export function createRightsCase(overrides: Partial<RightsCaseEntity> = {}) {
  const raw = {
    id: overrides.id ?? `rgt_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    status: overrides.status ?? "open",
    subjectRef: overrides.subjectRef ?? faker.lorem.word(),
    type: overrides.type ?? "access",
    ...overrides,
  };

  return rightsSchemas.RightsCase.parse(raw);
}

export function rightsCaseBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRightsCase(overrides));
}
