/**
 * GetSecurityEvent DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetSecurityEventParams } from "@consentrail/core/security-events";

export function createGetSecurityEventRequest(overrides: Partial<GetSecurityEventParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
