/**
 * ListSecurityEvent DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListSecurityEventsParams } from "@consentrail/core/security-events";

export function createListSecurityEventRequest(overrides: Partial<ListSecurityEventsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
