/**
 * Evidence DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Evidence Domain Module - Composition root
 *
 * DDD: Composition root for evidence domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  HashRepositoryAdapter,
  IntegrityProofRepositoryAdapter,
  OrphanRepositoryAdapter,
  VerifyRepositoryAdapter,
} from "@consentrail/adapters/evidence";
import { getIdGeneratorService } from "@consentrail/adapters";
import type { AdapterDynamoDBClient } from "@consentrail/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetEvidenceHash,
  ExecuteGetIntegrityProof,
  ExecuteIssueIntegrityProof,
  ExecuteListEvidenceHashes,
  ExecuteListIntegrityProofs,
  ExecuteOrphanEvidenceHash,
  ExecuteRegisterEvidenceHash,
  ExecuteVerifyIntegrityProof,
} from "@consentrail/services/evidence/usecases";
// Ports (interfaces)
import type {
  HashRepository,
  IntegrityProofRepository,
  OrphanRepository,
  VerifyRepository,
} from "@consentrail/services/evidence/ports";

export interface EvidenceDomainModule {
  repos: {
    hashes: HashRepository;
    integrityProofs: IntegrityProofRepository;
    orphans: OrphanRepository;
    verifies: VerifyRepository;
  };
  useCases: {
    hashes: {
      create: ExecuteRegisterEvidenceHash;
      get: ExecuteGetEvidenceHash;
      list: ExecuteListEvidenceHashes;
    };
    integrityProofs: {
      get: ExecuteGetIntegrityProof;
      list: ExecuteListIntegrityProofs;
    };
    orphans: {
      get: ExecuteOrphanEvidenceHash;
    };
    verifies: {
      get: ExecuteVerifyIntegrityProof;
    };
  };
}

export function buildEvidenceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): EvidenceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      hashes?: HashRepository;
      integrityProofs?: IntegrityProofRepository;
      orphans?: OrphanRepository;
      verifies?: VerifyRepository;
    } = {};

    obj.hashes = new HashRepositoryAdapter(dynamoClient);
    obj.integrityProofs = new IntegrityProofRepositoryAdapter(dynamoClient);
    obj.orphans = new OrphanRepositoryAdapter(dynamoClient);
    obj.verifies = new VerifyRepositoryAdapter(dynamoClient);
    return {
      hashes: obj.hashes!,
      integrityProofs: obj.integrityProofs!,
      orphans: obj.orphans!,
      verifies: obj.verifies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    hashes: {
      create: new ExecuteRegisterEvidenceHash(executionContext, idGenerator, repos.hashes),
      get: new ExecuteGetEvidenceHash(executionContext, idGenerator, repos.hashes),
      list: new ExecuteListEvidenceHashes(executionContext, idGenerator, repos.hashes),
    },
    integrityProofs: {
      get: new ExecuteGetIntegrityProof(executionContext, idGenerator, repos.integrityProofs),
      list: new ExecuteListIntegrityProofs(executionContext, idGenerator, repos.integrityProofs),
    },
    orphans: {
      get: new ExecuteOrphanEvidenceHash(executionContext, idGenerator, repos.orphans),
    },
    verifies: {
      get: new ExecuteVerifyIntegrityProof(executionContext, idGenerator, repos.verifies),
    },
  };
  return { repos, useCases: useCases as EvidenceDomainModule["useCases"] };
}
