/**
 * ComplianceAlertRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ComplianceAlertRepository Port
 *
 * DDD: Application port for compliancealertrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListComplianceAlertsInput, ListComplianceAlertsOutput } from "../dto/compliance-alert.dto";
export interface ComplianceAlertRepository {
  listComplianceAlerts(input: ListComplianceAlertsInput): Promise<ListComplianceAlertsOutput>;
}

export type { ListComplianceAlertsInput, ListComplianceAlertsOutput } from "../dto/compliance-alert.dto";
