/**
 * EvaluateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvaluateRepository Port
 *
 * DDD: Application port for evaluaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { EvaluateObligationContractInput, EvaluateObligationContractOutput } from "../dto/evaluate.dto";
export interface EvaluateRepository {
  evaluateObligationContract(input: EvaluateObligationContractInput): Promise<EvaluateObligationContractOutput>;
}

export type { EvaluateObligationContractInput, EvaluateObligationContractOutput } from "../dto/evaluate.dto";
