/**
 * GetRightsCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRightsCase } from "@consentrail/api-server/domains/rights/handlers";
import type { RightsDDDDependencies } from "@consentrail/api-server/domains/rights";
import { createRightsCase as createRightsCaseEntity } from "@consentrail/factories/rights";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { RIGHTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRightsCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RightsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RightsDDDDependencies>(
      RIGHTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createRightsCaseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRightsCase, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { caseId: entity.id };

    await getRightsCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRightsCase.execute).toHaveBeenCalledWith(expect.objectContaining({ caseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { caseId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetRightsCase, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getRightsCase(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
