/**
 * ListOwnerMediationGrants handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listOwnerMediationGrants } from "@consentrail/api-server/domains/consents/handlers";
import type { ConsentsDDDDependencies } from "@consentrail/api-server/domains/consents";
import { createOwnerMediationGrant as createOwnerMediationGrantEntity } from "@consentrail/factories/consents";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { CONSENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListOwnerMediationGrants", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConsentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConsentsDDDDependencies>(
      CONSENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createOwnerMediationGrantEntity({ orgId }),
      createOwnerMediationGrantEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListOwnerMediationGrants, "execute").mockResolvedValue(useCaseResult);

    await listOwnerMediationGrants(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListOwnerMediationGrants.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
