/**
 * GetRegulatorView DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetRegulatorViewParams } from "@consentrail/core/regulator-views";

export function createGetRegulatorViewRequest(overrides: Partial<GetRegulatorViewParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
