/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the rights domain.
 * Use these factories in tests to create test data.
 */

export { createCreateHandToCounselRequest } from "./hand-to-counsel/dto/create-hand-to-counsel.dto.factory.js";
export { createRightsCase } from "./rights-case/entity/rights-case.entity.factory.js";
