/**
 * ConsortiumRoleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsortiumRoleRepository Port
 *
 * DDD: Application port for consortiumrolerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AssignConsortiumRoleInput, AssignConsortiumRoleOutput, GetConsortiumRoleInput, GetConsortiumRoleOutput, ListConsortiumRolesInput, ListConsortiumRolesOutput } from "../dto/consortium-role.dto";
export interface ConsortiumRoleRepository {
  listConsortiumRoles(input: ListConsortiumRolesInput): Promise<ListConsortiumRolesOutput>;
  assignConsortiumRole(input: AssignConsortiumRoleInput): Promise<AssignConsortiumRoleOutput>;
  getConsortiumRole(input: GetConsortiumRoleInput): Promise<GetConsortiumRoleOutput>;
}

export type { AssignConsortiumRoleInput, AssignConsortiumRoleOutput, GetConsortiumRoleInput, GetConsortiumRoleOutput, ListConsortiumRolesInput, ListConsortiumRolesOutput } from "../dto/consortium-role.dto";
