/**
 * GoLiveGateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GoLiveGateRepository Port
 *
 * DDD: Application port for golivegaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetConsortiumGoLiveGateInput, GetConsortiumGoLiveGateOutput } from "../dto/go-live-gate.dto";
export interface GoLiveGateRepository {
  getConsortiumGoLiveGate(input: GetConsortiumGoLiveGateInput): Promise<GetConsortiumGoLiveGateOutput>;
}

export type { GetConsortiumGoLiveGateInput, GetConsortiumGoLiveGateOutput } from "../dto/go-live-gate.dto";
