/**
 * GetEvidenceHash handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getEvidenceHash } from "@consentrail/api-server/domains/evidence/handlers";
import type { EvidenceDDDDependencies } from "@consentrail/api-server/domains/evidence";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { EVIDENCE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetEvidenceHash", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EvidenceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EvidenceDDDDependencies>(
      EVIDENCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetEvidenceHash, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { hashId: entity.id };

    await getEvidenceHash(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetEvidenceHash.execute).toHaveBeenCalledWith(expect.objectContaining({ hashId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { hashId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetEvidenceHash, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getEvidenceHash(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
