/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./get-evidence-hash.handler.test.js";
export * from "./list-evidence-hashes.handler.test.js";
export * from "./register-evidence-hash.handler.test.js";
