/**
 * ExecuteOrphanEvidenceHash - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOrphanEvidenceHash Use Case
 *
 * DDD: Application use case for get Orphan.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OrphanEvidenceHashInput, OrphanEvidenceHashOutput } from "../dto/orphan.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { OrphanRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOrphanEvidenceHash {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly orphan: OrphanRepository
  ) {}

  async execute(input: OrphanEvidenceHashInput): Promise<OrphanEvidenceHashOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evdId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).hashId) {
      throw new ValidationError("hashId is required");
    }
    const hashId = (input as any).hashId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.orphan.orphanEvidenceHash({ hashId: hashId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${hashId}`);
    }

    return entity as OrphanEvidenceHashOutput;
  }
}
