/**
 * ExecuteListEvidenceHashes - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEvidenceHashes Use Case
 *
 * DDD: Application use case for list Hash.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEvidenceHashesInput, ListEvidenceHashesOutput } from "../dto/hash.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { HashRepository } from "../ports";

export class ExecuteListEvidenceHashes {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly hash: HashRepository
  ) {}

  async execute(input: ListEvidenceHashesInput): Promise<ListEvidenceHashesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evdId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.hash.listEvidenceHashes({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEvidenceHashesOutput;
  }
}
