/**
 * ExecuteGetIntegrityProof - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetIntegrityProof Use Case
 *
 * DDD: Application use case for get IntegrityProof.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetIntegrityProofInput, GetIntegrityProofOutput } from "../dto/integrity-proof.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { IntegrityProofRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetIntegrityProof {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly integrityProof: IntegrityProofRepository
  ) {}

  async execute(input: GetIntegrityProofInput): Promise<GetIntegrityProofOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evdId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).proofId) {
      throw new ValidationError("proofId is required");
    }
    const proofId = (input as any).proofId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.integrityProof.getIntegrityProof({ proofId: proofId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${proofId}`);
    }

    return entity as GetIntegrityProofOutput;
  }
}
