/**
 * IntegrityProof Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { IntegrityProofEntity } from "@consentrail/core/evidence/models/index.js";
import { evidenceSchemas } from "@consentrail/core/evidence";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "evd";

export function createIntegrityProof(overrides: Partial<IntegrityProofEntity> = {}) {
  const raw = {
    id: overrides.id ?? `prf_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    artefactRef: overrides.artefactRef ?? faker.lorem.word(),
    issuedAt: overrides.issuedAt ?? new Date().toISOString(),
    proof: overrides.proof ?? faker.lorem.word(),
    ...overrides,
  };

  return evidenceSchemas.IntegrityProof.parse(raw);
}

export function integrityProofBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createIntegrityProof(overrides));
}
