/**
 * Handlers for HandToCounsel
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RightsDomainModule } from "../dependencies/rights-ddd.dependencies.js";
import type { HandRightsCaseToCounselInput } from "@consentrail/services/rights";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/rights-cases/{caseId}/hand-to-counsel
 * Operation: handRightsCaseToCounsel
 */
export async function handRightsCaseToCounsel(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: RightsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: HandRightsCaseToCounselInput = {
    caseId: request.params.caseId,
  };
  const result = await deps.useCases.handToCounsels.get.execute(input);
  return reply.code(200).send(result);
}


