/**
 * ConsentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsentRepository Port
 *
 * DDD: Application port for consentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CaptureConsentInput, CaptureConsentOutput, GetConsentRecordInput, GetConsentRecordOutput, ListConsentRecordsInput, ListConsentRecordsOutput } from "../dto/consent.dto";
export interface ConsentRepository {
  listConsentRecords(input: ListConsentRecordsInput): Promise<ListConsentRecordsOutput>;
  captureConsent(input: CaptureConsentInput): Promise<CaptureConsentOutput>;
  getConsentRecord(input: GetConsentRecordInput): Promise<GetConsentRecordOutput>;
}

export type { CaptureConsentInput, CaptureConsentOutput, GetConsentRecordInput, GetConsentRecordOutput, ListConsentRecordsInput, ListConsentRecordsOutput } from "../dto/consent.dto";
