/**
 * DenyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DenyRepository Port
 *
 * DDD: Application port for denyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DenyOwnerMediationGrantInput, DenyOwnerMediationGrantOutput } from "../dto/deny.dto";
export interface DenyRepository {
  denyOwnerMediationGrant(input: DenyOwnerMediationGrantInput): Promise<DenyOwnerMediationGrantOutput>;
}

export type { DenyOwnerMediationGrantInput, DenyOwnerMediationGrantOutput } from "../dto/deny.dto";
