/**
 * ProcessingStopRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProcessingStopRepository Port
 *
 * DDD: Application port for processingstoprepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetProcessingStopStateInput, GetProcessingStopStateOutput, RetryProcessingStopPushInput, RetryProcessingStopPushOutput } from "../dto/processing-stop.dto";
export interface ProcessingStopRepository {
  getProcessingStopState(input: GetProcessingStopStateInput): Promise<GetProcessingStopStateOutput>;
  retryProcessingStopPush(input: RetryProcessingStopPushInput): Promise<RetryProcessingStopPushOutput>;
}

export type { GetProcessingStopStateInput, GetProcessingStopStateOutput, RetryProcessingStopPushInput, RetryProcessingStopPushOutput } from "../dto/processing-stop.dto";
