/**
 * WithdrawRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WithdrawRepository Port
 *
 * DDD: Application port for withdrawrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { WithdrawConsentInput, WithdrawConsentOutput } from "../dto/withdraw.dto";
export interface WithdrawRepository {
  withdrawConsent(input: WithdrawConsentInput): Promise<WithdrawConsentOutput>;
}

export type { WithdrawConsentInput, WithdrawConsentOutput } from "../dto/withdraw.dto";
