/**
 * ExecuteListComplianceAlerts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListComplianceAlerts Use Case
 *
 * DDD: Application use case for list ComplianceAlert.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListComplianceAlertsInput, ListComplianceAlertsOutput } from "../dto/compliance-alert.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { ComplianceAlertRepository } from "../ports";

export class ExecuteListComplianceAlerts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly complianceAlert: ComplianceAlertRepository
  ) {}

  async execute(input: ListComplianceAlertsInput): Promise<ListComplianceAlertsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.oblId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.complianceAlert.listComplianceAlerts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListComplianceAlertsOutput;
  }
}
