/**
 * ExecuteListObligationContracts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListObligationContracts Use Case
 *
 * DDD: Application use case for list Obligation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListObligationContractsInput, ListObligationContractsOutput } from "../dto/obligation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { ObligationRepository } from "../ports";

export class ExecuteListObligationContracts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly obligation: ObligationRepository
  ) {}

  async execute(input: ListObligationContractsInput): Promise<ListObligationContractsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.oblId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.obligation.listObligationContracts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListObligationContractsOutput;
  }
}
