/**
 * ExecuteGetObligationContract - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetObligationContract Use Case
 *
 * DDD: Application use case for get Obligation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetObligationContractInput, GetObligationContractOutput } from "../dto/obligation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { ObligationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetObligationContract {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly obligation: ObligationRepository
  ) {}

  async execute(input: GetObligationContractInput): Promise<GetObligationContractOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.oblId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).contractId) {
      throw new ValidationError("contractId is required");
    }
    const contractId = (input as any).contractId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.obligation.getObligationContract({ contractId: contractId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${contractId}`);
    }

    return entity as GetObligationContractOutput;
  }
}
