/**
 * ExecuteWaiveComplianceAlert - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteWaiveComplianceAlert Use Case
 *
 * DDD: Application use case for get Waive.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { WaiveComplianceAlertInput, WaiveComplianceAlertOutput } from "../dto/waive.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { WaiveRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteWaiveComplianceAlert {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly waive: WaiveRepository
  ) {}

  async execute(input: WaiveComplianceAlertInput): Promise<WaiveComplianceAlertOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.oblId();

    // All field names extracted from OpenAPI spec: expiresAt, note
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).alertId) {
      throw new ValidationError("alertId is required");
    }
    const alertId = (input as any).alertId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.waive.waiveComplianceAlert({ alertId: alertId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${alertId}`);
    }

    return entity as WaiveComplianceAlertOutput;
  }
}
