/**
 * ExecuteCreateObligationContract - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateObligationContract Use Case
 *
 * DDD: Application use case for create Obligation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateObligationContractInput, CreateObligationContractOutput } from "../dto/obligation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { ObligationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateObligationContract {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly obligation: ObligationRepository
  ) {}

  async execute(input: CreateObligationContractInput): Promise<CreateObligationContractOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.oblId();

    // All field names extracted from OpenAPI spec: controllerId, processorId, termsHash
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.processorId) {
      throw new ValidationError("processorId is required");
    }
    if (!input.termsHash) {
      throw new ValidationError("termsHash is required");
    }
    if (!input.controllerId) {
      throw new ValidationError("controllerId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (obligations domain)
    const entityId = this.idGenerator.oblId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.obligation.createObligationContract({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateObligationContractOutput;
  }
}
