/**
 * ExecuteCreateTripleBlindPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateTripleBlindPolicy Use Case
 *
 * DDD: Application use case for create TripleBlindPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateTripleBlindPolicyInput, CreateTripleBlindPolicyOutput } from "../dto/triple-blind-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { TripleBlindPolicyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateTripleBlindPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly tripleBlindPolicy: TripleBlindPolicyRepository
  ) {}

  async execute(input: CreateTripleBlindPolicyInput): Promise<CreateTripleBlindPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tblId();

    // All field names extracted from OpenAPI spec: consumerLearns, name, operatorLearns, providerLearns
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (triple-blind-exchange domain)
    const entityId = this.idGenerator.tblId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.tripleBlindPolicy.createTripleBlindPolicy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateTripleBlindPolicyOutput;
  }
}
