/**
 * ExecuteEnableTripleBlindPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteEnableTripleBlindPolicy Use Case
 *
 * DDD: Application use case for update Enable.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { EnableTripleBlindPolicyInput, EnableTripleBlindPolicyOutput } from "../dto/enable.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { EnableRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteEnableTripleBlindPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly enable: EnableRepository
  ) {}

  async execute(input: EnableTripleBlindPolicyInput): Promise<EnableTripleBlindPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tblId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyId) {
      throw new ValidationError("policyId is required");
    }
    const policyId = (input as any).policyId;

    const existing = await (this.enable as any).getTripleBlindPolicy?.({
      policyId,
      orgId: this.context.getOrgId(),
      correlationId,
    }) ?? { policyId };
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${policyId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.enable.enableTripleBlindPolicy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as EnableTripleBlindPolicyOutput;
  }
}
