/**
 * ExecuteDisableTripleBlindPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDisableTripleBlindPolicy Use Case
 *
 * DDD: Application use case for update Disable.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DisableTripleBlindPolicyInput, DisableTripleBlindPolicyOutput } from "../dto/disable.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { DisableRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteDisableTripleBlindPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly disable: DisableRepository
  ) {}

  async execute(input: DisableTripleBlindPolicyInput): Promise<DisableTripleBlindPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tblId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyId) {
      throw new ValidationError("policyId is required");
    }
    const policyId = (input as any).policyId;

    // Load existing entity (action repos expose enable/disable only — soft-load via action)
    const existing = await (this.disable as any).getTripleBlindPolicy?.({
      policyId,
      orgId: this.context.getOrgId(),
      correlationId,
    }) ?? { policyId };
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.disable.disableTripleBlindPolicy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as DisableTripleBlindPolicyOutput;
  }
}
