/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Rights Domain Use Cases
 * 
 * List of all use case names for the rights domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const RIGHTS_USE_CASES = [
  "executeCloseRightsCase",
  "executeGetRightsCase",
  "executeHandRightsCaseToCounsel",
  "executeListRightsCases",
  "executeOpenRightsCase"
] as const;
