/**
 * ExecuteListCounselGates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCounselGates Use Case
 *
 * DDD: Application use case for list CounselGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCounselGatesInput, ListCounselGatesOutput } from "../dto/counsel-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { CounselGateRepository } from "../ports";

export class ExecuteListCounselGates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly counselGate: CounselGateRepository
  ) {}

  async execute(input: ListCounselGatesInput): Promise<ListCounselGatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cngId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.counselGate.listCounselGates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCounselGatesOutput;
  }
}
