/**
 * ExecuteDecideCounselGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDecideCounselGate Use Case
 *
 * DDD: Application use case for get Decide.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DecideCounselGateInput, DecideCounselGateOutput } from "../dto/decide.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { DecideRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDecideCounselGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decide: DecideRepository
  ) {}

  async execute(input: DecideCounselGateInput): Promise<DecideCounselGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cngId();

    // All field names extracted from OpenAPI spec: basis, decision
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).gateId) {
      throw new ValidationError("gateId is required");
    }
    const gateId = (input as any).gateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.decide.decideCounselGate({ gateId: gateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${gateId}`);
    }

    return entity as DecideCounselGateOutput;
  }
}
