/**
 * ExecuteOpenCounselGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenCounselGate Use Case
 *
 * DDD: Application use case for get CounselGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenCounselGateInput, OpenCounselGateOutput } from "../dto/counsel-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { CounselGateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOpenCounselGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly counselGate: CounselGateRepository
  ) {}

  async execute(input: OpenCounselGateInput): Promise<OpenCounselGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cngId();

    // All field names extracted from OpenAPI spec: evidenceHashId, rightsCaseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).evidenceHashId) {
      throw new ValidationError("evidenceHashId is required");
    }
    const evidencehashId = (input as any).evidenceHashId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.counselGate.openCounselGate({ evidenceHashId: evidencehashId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${evidencehashId}`);
    }

    return entity as OpenCounselGateOutput;
  }
}
