/**
 * Handlers for Acknowledge
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SecurityEventsDomainModule } from "../dependencies/security-events-ddd.dependencies.js";
import type { AcknowledgeSecurityEventInput } from "@consentrail/services/security-events";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/security-events/{eventId}/acknowledge
 * Operation: acknowledgeSecurityEvent
 */
export async function acknowledgeSecurityEvent(
  request: FastifyRequest<{ Params: { eventId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SecurityEventsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AcknowledgeSecurityEventInput = {
    eventId: request.params.eventId,
  };
  const result = await deps.useCases.acknowledges.get.execute(input);
  return reply.code(200).send(result);
}


