/**
 * CreateAttest DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AttestConsortiumRoleParams } from "@consentrail/core/consortium-roles";

export function createCreateAttestRequest(overrides: Partial<AttestConsortiumRoleParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
