/**
 * ComplianceAlert Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ComplianceAlertEntity } from "@consentrail/core/obligations/models/index.js";
import { obligationsSchemas } from "@consentrail/core/obligations";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "obl";

export function createComplianceAlert(overrides: Partial<ComplianceAlertEntity> = {}) {
  const raw = {
    id: overrides.id ?? `alt_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    contractId: overrides.contractId ?? `obl_${ulid().toLowerCase()}`,
    status: overrides.status ?? "compliant",
    ...overrides,
  };

  return obligationsSchemas.ComplianceAlert.parse(raw);
}

export function complianceAlertBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createComplianceAlert(overrides));
}
