/**
 * ExecuteGetConsortiumRole - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetConsortiumRole Use Case
 *
 * DDD: Application use case for get ConsortiumRole.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetConsortiumRoleInput, GetConsortiumRoleOutput } from "../dto/consortium-role.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { ConsortiumRoleRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetConsortiumRole {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly consortiumRole: ConsortiumRoleRepository
  ) {}

  async execute(input: GetConsortiumRoleInput): Promise<GetConsortiumRoleOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).roleId) {
      throw new ValidationError("roleId is required");
    }
    const roleId = (input as any).roleId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.consortiumRole.getConsortiumRole({ roleId: roleId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${roleId}`);
    }

    return entity as GetConsortiumRoleOutput;
  }
}
