/**
 * Handlers for ComplianceAlert
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ObligationsDomainModule } from "../dependencies/obligations-ddd.dependencies.js";
import type { ListComplianceAlertsInput } from "@consentrail/services/obligations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/compliance-alerts
 * Operation: listComplianceAlerts
 */
export async function listComplianceAlerts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], contractId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ObligationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListComplianceAlertsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.complianceAlerts.list.execute(input);
  return reply.code(200).send(result);
}


