/**
 * Handlers for Evaluate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ObligationsDomainModule } from "../dependencies/obligations-ddd.dependencies.js";
import type { EvaluateObligationContractInput } from "@consentrail/services/obligations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/obligations/{contractId}/evaluate
 * Operation: evaluateObligationContract
 */
export async function evaluateObligationContract(
  request: FastifyRequest<{ Params: { contractId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ObligationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: EvaluateObligationContractInput = {
    contractId: request.params.contractId,
  };
  const result = await deps.useCases.evaluates.create.execute(input);
  return reply.code(200).send(result);
}


