/**
 * Handlers for Waive
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ObligationsDomainModule } from "../dependencies/obligations-ddd.dependencies.js";
import type { WaiveComplianceAlertInput } from "@consentrail/services/obligations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/compliance-alerts/{alertId}/waive
 * Operation: waiveComplianceAlert
 */
export async function waiveComplianceAlert(
  request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ObligationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: WaiveComplianceAlertInput = {
    alertId: request.params.alertId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.waives.get.execute(input);
  return reply.code(200).send(result);
}


