/**
 * ConsortiumRole Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ConsortiumRoleEntity } from "@consentrail/core/consortium-roles/models/index.js";
import { consortiumRolesSchemas } from "@consentrail/core/consortium-roles";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cnr";

export function createConsortiumRole(overrides: Partial<ConsortiumRoleEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cnr_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    attested: overrides.attested ?? faker.datatype.boolean(),
    kind: overrides.kind ?? "controller",
    memberId: overrides.memberId ?? faker.string.uuid(),
    ...overrides,
  };

  return consortiumRolesSchemas.ConsortiumRole.parse(raw);
}

export function consortiumRoleBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createConsortiumRole(overrides));
}
