/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the security-events domain.
 * Use these factories in tests to create test data.
 */

export { createCreateAcknowledgeRequest } from "./acknowledge/dto/create-acknowledge.dto.factory.js";
export { createSecurityEvent } from "./security-event/entity/security-event.entity.factory.js";
