/**
 * ListIntegrityProofs handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listIntegrityProofs } from "@consentrail/api-server/domains/evidence/handlers";
import type { EvidenceDDDDependencies } from "@consentrail/api-server/domains/evidence";
import { createIntegrityProof as createIntegrityProofEntity } from "@consentrail/factories/evidence";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@consentrail/tests/shared";
import { EVIDENCE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListIntegrityProofs", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EvidenceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EvidenceDDDDependencies>(
      EVIDENCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createIntegrityProofEntity({ orgId }),
      createIntegrityProofEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListIntegrityProofs, "execute").mockResolvedValue(useCaseResult);

    await listIntegrityProofs(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListIntegrityProofs.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
