/**
 * SecurityEvents DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SecurityEvents Domain Module - Composition root
 *
 * DDD: Composition root for security-events domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcknowledgeRepositoryAdapter,
  SecurityEventRepositoryAdapter,
} from "@consentrail/adapters/security-events";
import { getIdGeneratorService } from "@consentrail/adapters";
import type { AdapterDynamoDBClient } from "@consentrail/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcknowledgeSecurityEvent,
  ExecuteGetSecurityEvent,
  ExecuteListSecurityEvents,
  ExecuteRecordSecurityEvent,
} from "@consentrail/services/security-events/usecases";
// Ports (interfaces)
import type {
  AcknowledgeRepository,
  SecurityEventRepository,
} from "@consentrail/services/security-events/ports";

export interface SecurityEventsDomainModule {
  repos: {
    acknowledges: AcknowledgeRepository;
    securityEvents: SecurityEventRepository;
  };
  useCases: {
    acknowledges: {
      get: ExecuteAcknowledgeSecurityEvent;
    };
    securityEvents: {
      get: ExecuteGetSecurityEvent;
      list: ExecuteListSecurityEvents;
    };
  };
}

export function buildSecurityEventsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SecurityEventsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acknowledges?: AcknowledgeRepository;
      securityEvents?: SecurityEventRepository;
    } = {};

    obj.acknowledges = new AcknowledgeRepositoryAdapter(dynamoClient);
    obj.securityEvents = new SecurityEventRepositoryAdapter(dynamoClient);
    return {
      acknowledges: obj.acknowledges!,
      securityEvents: obj.securityEvents!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acknowledges: {
      get: new ExecuteAcknowledgeSecurityEvent(executionContext, idGenerator, repos.acknowledges),
    },
    securityEvents: {
      get: new ExecuteGetSecurityEvent(executionContext, idGenerator, repos.securityEvents),
      list: new ExecuteListSecurityEvents(executionContext, idGenerator, repos.securityEvents),
    },
  };
  return { repos, useCases: useCases as SecurityEventsDomainModule["useCases"] };
}
