/**
 * Routes for Enable
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { enableTripleBlindPolicy } from "../handlers/enable.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function enableRoutes(fastify: FastifyInstance) {
  // POST /v1/triple-blind-policies/{policyId}/enable (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/triple-blind-policies/:policyId/enable",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTripleBlindExchangeDependenciesForRequest();
        await enableTripleBlindPolicy(request, reply, deps);
      });
    }
  );


}
