/**
 * Acknowledge DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Acknowledge DTOs
 *
 * DDD: Application DTOs for Acknowledge use cases.
 */

import type { AcknowledgeComplianceAlertParams } from "@consentrail/core/obligations/types";

export type AcknowledgeComplianceAlertInput = AcknowledgeComplianceAlertParams;

export type AcknowledgeComplianceAlertOutput = {};
