/**
 * Waive DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: obligations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Waive DTOs
 *
 * DDD: Application DTOs for Waive use cases.
 */

import type { WaiveComplianceAlertParams, WaiveComplianceAlertRequestInput } from "@consentrail/core/obligations/types";

export type WaiveComplianceAlertInput = WaiveComplianceAlertParams & WaiveComplianceAlertRequestInput;

export type WaiveComplianceAlertOutput = {};
