/**
 * ExecuteListRightsCases - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRightsCases Use Case
 *
 * DDD: Application use case for list RightsCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRightsCasesInput, ListRightsCasesOutput } from "../dto/rights-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { RightsCaseRepository } from "../ports";

export class ExecuteListRightsCases {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rightsCase: RightsCaseRepository
  ) {}

  async execute(input: ListRightsCasesInput): Promise<ListRightsCasesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rgtId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.rightsCase.listRightsCases({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRightsCasesOutput;
  }
}
