/**
 * ExecuteOpenRightsCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenRightsCase Use Case
 *
 * DDD: Application use case for get RightsCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenRightsCaseInput, OpenRightsCaseOutput } from "../dto/rights-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { RightsCaseRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteOpenRightsCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rightsCase: RightsCaseRepository
  ) {}

  async execute(input: OpenRightsCaseInput): Promise<OpenRightsCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rgtId();

    // All field names extracted from OpenAPI spec: slaDueAt, subjectRef, type
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.rightsCase.openRightsCase({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as OpenRightsCaseOutput;
  }
}
