/**
 * ExecuteGetRightsCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetRightsCase Use Case
 *
 * DDD: Application use case for get RightsCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetRightsCaseInput, GetRightsCaseOutput } from "../dto/rights-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@consentrail/services/_shared/index.js";
import type { RightsCaseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetRightsCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rightsCase: RightsCaseRepository
  ) {}

  async execute(input: GetRightsCaseInput): Promise<GetRightsCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rgtId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).caseId) {
      throw new ValidationError("caseId is required");
    }
    const caseId = (input as any).caseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.rightsCase.getRightsCase({ caseId: caseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${caseId}`);
    }

    return entity as GetRightsCaseOutput;
  }
}
