/**
 * Handlers for DryRun
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TripleBlindExchangeDomainModule } from "../dependencies/triple-blind-exchange-ddd.dependencies.js";
import type { DryRunTripleBlindPolicyInput } from "@consentrail/services/triple-blind-exchange";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/triple-blind-policies/{policyId}/dry-run
 * Operation: dryRunTripleBlindPolicy
 */
export async function dryRunTripleBlindPolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TripleBlindExchangeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DryRunTripleBlindPolicyInput = {
    policyId: request.params.policyId,
  };
  const result = await deps.useCases.dryRuns.get.execute(input);
  return reply.code(200).send(result);
}


