/**
 * Routes for Decide
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { decideCounselGate } from "../handlers/decide.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function decideRoutes(fastify: FastifyInstance) {
  // POST /v1/counsel-gates/{gateId}/decide (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/counsel-gates/:gateId/decide",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { gateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCounselGatesDependenciesForRequest();
        await decideCounselGate(request, reply, deps);
      });
    }
  );


}
