/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@consentrail/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@consentrail/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@consentrail/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _consents from "./consents/index.js";
import * as _consortiumRoles from "./consortium-roles/index.js";
import * as _counselGates from "./counsel-gates/index.js";
import * as _evidence from "./evidence/index.js";
import * as _identity from "./identity/index.js";
import * as _obligations from "./obligations/index.js";
import * as _regulatorViews from "./regulator-views/index.js";
import * as _rights from "./rights/index.js";
import * as _securityEvents from "./security-events/index.js";
import * as _tripleBlindExchange from "./triple-blind-exchange/index.js";

// Export as namespaces
export const consents = _consents;
export const consortiumRoles = _consortiumRoles;
export const counselGates = _counselGates;
export const evidence = _evidence;
export const identity = _identity;
export const obligations = _obligations;
export const regulatorViews = _regulatorViews;
export const rights = _rights;
export const securityEvents = _securityEvents;
export const tripleBlindExchange = _tripleBlindExchange;
