/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * CounselGates Domain Use Cases
 * 
 * List of all use case names for the counsel-gates domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const COUNSELGATES_USE_CASES = [
  "executeDecideCounselGate",
  "executeGetCounselGate",
  "executeListCounselGates",
  "executeOpenCounselGate"
] as const;
