/**
 * Repository interface for RegulatorView
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RegulatorViewEntity
} from "../models/regulator-view.entity.js";
import type {
  ListRegulatorViewsParams,
  RegulatorView
} from "../types/index.js";
/**
 * RegulatorViewRepository Interface
 */
export interface RegulatorViewRepository extends CreateReadRepository<RegulatorViewEntity, RegulatorView, string, ListRegulatorViewsParams> {

}
