/**
 * Routes for IntegrityProof
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getIntegrityProof, issueIntegrityProof, listIntegrityProofs } from "../handlers/integrity-proof.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function integrityProofRoutes(fastify: FastifyInstance) {
  // POST /v1/evidence/integrity-proofs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/evidence/integrity-proofs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await issueIntegrityProof(request, reply, deps);
      });
    }
  );


  // GET /v1/evidence/integrity-proofs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/evidence/integrity-proofs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await listIntegrityProofs(request, reply, deps);
      });
    }
  );


  // GET /v1/evidence/integrity-proofs/{proofId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/evidence/integrity-proofs/:proofId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { proofId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await getIntegrityProof(request, reply, deps);
      });
    }
  );


}
