/**
 * Routes for Verify
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { verifyIntegrityProof } from "../handlers/verify.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function verifyRoutes(fastify: FastifyInstance) {
  // POST /v1/evidence/integrity-proofs/{proofId}/verify (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/evidence/integrity-proofs/:proofId/verify",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { proofId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await verifyIntegrityProof(request, reply, deps);
      });
    }
  );


}
