/**
 * HashRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HashRepository Port
 *
 * DDD: Application port for hashrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEvidenceHashInput, GetEvidenceHashOutput, ListEvidenceHashesInput, ListEvidenceHashesOutput, RegisterEvidenceHashInput, RegisterEvidenceHashOutput } from "../dto/hash.dto";
export interface HashRepository {
  listEvidenceHashes(input: ListEvidenceHashesInput): Promise<ListEvidenceHashesOutput>;
  registerEvidenceHash(input: RegisterEvidenceHashInput): Promise<RegisterEvidenceHashOutput>;
  getEvidenceHash(input: GetEvidenceHashInput): Promise<GetEvidenceHashOutput>;
}

export type { GetEvidenceHashInput, GetEvidenceHashOutput, ListEvidenceHashesInput, ListEvidenceHashesOutput, RegisterEvidenceHashInput, RegisterEvidenceHashOutput } from "../dto/hash.dto";
