/**
 * IntegrityProofRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IntegrityProofRepository Port
 *
 * DDD: Application port for integrityproofrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetIntegrityProofInput, GetIntegrityProofOutput, IssueIntegrityProofInput, IssueIntegrityProofOutput, ListIntegrityProofsInput, ListIntegrityProofsOutput } from "../dto/integrity-proof.dto";
export interface IntegrityProofRepository {
  listIntegrityProofs(input: ListIntegrityProofsInput): Promise<ListIntegrityProofsOutput>;
  issueIntegrityProof(input: IssueIntegrityProofInput): Promise<IssueIntegrityProofOutput>;
  getIntegrityProof(input: GetIntegrityProofInput): Promise<GetIntegrityProofOutput>;
}

export type { GetIntegrityProofInput, GetIntegrityProofOutput, IssueIntegrityProofInput, IssueIntegrityProofOutput, ListIntegrityProofsInput, ListIntegrityProofsOutput } from "../dto/integrity-proof.dto";
