/**
 * OrphanRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OrphanRepository Port
 *
 * DDD: Application port for orphanrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { OrphanEvidenceHashInput, OrphanEvidenceHashOutput } from "../dto/orphan.dto";
export interface OrphanRepository {
  orphanEvidenceHash(input: OrphanEvidenceHashInput): Promise<OrphanEvidenceHashOutput>;
}

export type { OrphanEvidenceHashInput, OrphanEvidenceHashOutput } from "../dto/orphan.dto";
