/**
 * VerifyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerifyRepository Port
 *
 * DDD: Application port for verifyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { VerifyIntegrityProofInput, VerifyIntegrityProofOutput } from "../dto/verify.dto";
export interface VerifyRepository {
  verifyIntegrityProof(input: VerifyIntegrityProofInput): Promise<VerifyIntegrityProofOutput>;
}

export type { VerifyIntegrityProofInput, VerifyIntegrityProofOutput } from "../dto/verify.dto";
