/**
 * RegulatorView Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RegulatorViewEntity } from "@consentrail/core/regulator-views/models/index.js";
import { regulatorViewsSchemas } from "@consentrail/core/regulator-views";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rgv";

export function createRegulatorView(overrides: Partial<RegulatorViewEntity> = {}) {
  const raw = {
    id: overrides.id ?? `rgv_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    includesPersonalData: overrides.includesPersonalData ?? faker.datatype.boolean(),
    regulatorId: overrides.regulatorId ?? faker.string.uuid(),
    scope: overrides.scope ?? [],
    ...overrides,
  };

  return regulatorViewsSchemas.RegulatorView.parse(raw);
}

export function regulatorViewBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRegulatorView(overrides));
}
