/**
 * RightsCase Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/rights.openapi.types.js";
import { schemas } from "../schemas/rights.schemas.js";

/**
 * Entity: RightsCaseEntity
 * Description: Represents the RightsCase domain model.
 * Source: schemas.RightsCase
 * Type: Domain Entity (API)
 */
export const RightsCaseEntitySchema = schemas.RightsCase;
export type RightsCaseEntity = components["schemas"]["RightsCase"];
