/**
 * Routes for GoLiveGate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getConsortiumGoLiveGate } from "../handlers/go-live-gate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function goLiveGateRoutes(fastify: FastifyInstance) {
  // GET /v1/consortium-roles/go-live-gate (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/consortium-roles/go-live-gate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsortiumRolesDependenciesForRequest();
        await getConsortiumGoLiveGate(request, reply, deps);
      });
    }
  );


}
