/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { goLiveGateRoutes } from "./go-live-gate.routes.js";
export { attestRoutes } from "./attest.routes.js";
export { consortiumRoleRoutes } from "./consortium-role.routes.js";
