/**
 * OwnerMediationGrant Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { OwnerMediationGrantEntity } from "@consentrail/core/consents/models/index.js";
import { consentsSchemas } from "@consentrail/core/consents";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cns";

export function createOwnerMediationGrant(overrides: Partial<OwnerMediationGrantEntity> = {}) {
  const raw = {
    id: overrides.id ?? `omg_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    consentId: overrides.consentId ?? `cns_${ulid().toLowerCase()}`,
    requestingMemberId: overrides.requestingMemberId ?? faker.string.uuid(),
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return consentsSchemas.OwnerMediationGrant.parse(raw);
}

export function ownerMediationGrantBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createOwnerMediationGrant(overrides));
}
