/**
 * Attest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attest DTOs
 *
 * DDD: Application DTOs for Attest use cases.
 */

import type { AttestConsortiumRoleParams } from "@consentrail/core/consortium-roles/types";

export type AttestConsortiumRoleInput = AttestConsortiumRoleParams;

export type AttestConsortiumRoleOutput = {};
