/**
 * GoLiveGate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GoLiveGate DTOs
 *
 * DDD: Application DTOs for GoLiveGate use cases.
 */

export type GetConsortiumGoLiveGateInput = {};

export type GetConsortiumGoLiveGateOutput = {};
