/**
 * SecurityEventRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SecurityEventRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SecurityEventRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SecurityEventRepository,
} from "@consentrail/services/security-events";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SecurityEventRepositoryDdb } from "./security-event-repository.ddb.js";

/**
 * SecurityEventRepositoryAdapter
 *
 * Implements SecurityEventRepository port for infrastructure layer.
 */
export class SecurityEventRepositoryAdapter implements SecurityEventRepository {
  private readonly ddb: SecurityEventRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SecurityEventRepositoryDdb(this.dynamoClient);
  }

  async listSecurityEvents(input: Parameters<SecurityEventRepository['listSecurityEvents']>[0]): Promise<Awaited<ReturnType<SecurityEventRepository['listSecurityEvents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSecurityEvents(input);
  }

  async recordSecurityEvent(input: Parameters<SecurityEventRepository['recordSecurityEvent']>[0]): Promise<Awaited<ReturnType<SecurityEventRepository['recordSecurityEvent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordSecurityEvent(input);
  }

  async getSecurityEvent(input: Parameters<SecurityEventRepository['getSecurityEvent']>[0]): Promise<Awaited<ReturnType<SecurityEventRepository['getSecurityEvent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSecurityEvent(input);
  }
}
