/**
 * IntegrityProof Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/evidence.openapi.types.js";
import { schemas } from "../schemas/evidence.schemas.js";

/**
 * Entity: IntegrityProofEntity
 * Description: Represents the IntegrityProof domain model.
 * Source: schemas.IntegrityProof
 * Type: Domain Entity (API)
 */
export const IntegrityProofEntitySchema = schemas.IntegrityProof;
export type IntegrityProofEntity = components["schemas"]["IntegrityProof"];
