/**
 * Handlers for Hash
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidenceDomainModule } from "../dependencies/evidence-ddd.dependencies.js";
import type { GetEvidenceHashInput, ListEvidenceHashesInput, RegisterEvidenceHashInput } from "@consentrail/services/evidence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/evidence/hashes
 * Operation: listEvidenceHashes
 */
export async function listEvidenceHashes(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEvidenceHashesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.hashes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/evidence/hashes
 * Operation: registerEvidenceHash
 */
export async function registerEvidenceHash(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterEvidenceHashInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.hashes.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/evidence/hashes/{hashId}
 * Operation: getEvidenceHash
 */
export async function getEvidenceHash(
  request: FastifyRequest<{ Params: { hashId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEvidenceHashInput = {
    hashId: request.params.hashId,
  };
  const result = await deps.useCases.hashes.get.execute(input);
  return reply.code(200).send(result);
}


