/**
 * Handlers for IntegrityProof
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidenceDomainModule } from "../dependencies/evidence-ddd.dependencies.js";
import type { GetIntegrityProofInput, IssueIntegrityProofInput, ListIntegrityProofsInput } from "@consentrail/services/evidence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/evidence/integrity-proofs
 * Operation: listIntegrityProofs
 */
export async function listIntegrityProofs(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListIntegrityProofsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.integrityProofs.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/evidence/integrity-proofs
 * Operation: issueIntegrityProof
 */
export async function issueIntegrityProof(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: IssueIntegrityProofInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.integrityProofs.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/evidence/integrity-proofs/{proofId}
 * Operation: getIntegrityProof
 */
export async function getIntegrityProof(
  request: FastifyRequest<{ Params: { proofId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetIntegrityProofInput = {
    proofId: request.params.proofId,
  };
  const result = await deps.useCases.integrityProofs.get.execute(input);
  return reply.code(200).send(result);
}


