/**
 * Handlers for Orphan
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidenceDomainModule } from "../dependencies/evidence-ddd.dependencies.js";
import type { OrphanEvidenceHashInput } from "@consentrail/services/evidence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/evidence/hashes/{hashId}/orphan
 * Operation: orphanEvidenceHash
 */
export async function orphanEvidenceHash(
  request: FastifyRequest<{ Params: { hashId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OrphanEvidenceHashInput = {
    hashId: request.params.hashId,
  };
  const result = await deps.useCases.orphans.get.execute(input);
  return reply.code(200).send(result);
}


