/**
 * Handlers for Verify
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidenceDomainModule } from "../dependencies/evidence-ddd.dependencies.js";
import type { VerifyIntegrityProofInput } from "@consentrail/services/evidence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/evidence/integrity-proofs/{proofId}/verify
 * Operation: verifyIntegrityProof
 */
export async function verifyIntegrityProof(
  request: FastifyRequest<{ Params: { proofId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: VerifyIntegrityProofInput = {
    proofId: request.params.proofId,
  };
  const result = await deps.useCases.verifies.get.execute(input);
  return reply.code(200).send(result);
}


