/**
 * SecurityEventRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SecurityEventRepository Port
 *
 * DDD: Application port for securityeventrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSecurityEventInput, GetSecurityEventOutput, ListSecurityEventsInput, ListSecurityEventsOutput, RecordSecurityEventInput, RecordSecurityEventOutput } from "../dto/security-event.dto";
export interface SecurityEventRepository {
  listSecurityEvents(input: ListSecurityEventsInput): Promise<ListSecurityEventsOutput>;
  recordSecurityEvent(input: RecordSecurityEventInput): Promise<RecordSecurityEventOutput>;
  getSecurityEvent(input: GetSecurityEventInput): Promise<GetSecurityEventOutput>;
}

export type { GetSecurityEventInput, GetSecurityEventOutput, ListSecurityEventsInput, ListSecurityEventsOutput, RecordSecurityEventInput, RecordSecurityEventOutput } from "../dto/security-event.dto";
