/**
 * RegulatorViewRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RegulatorViewRepository Port
 *
 * DDD: Application port for regulatorviewrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetRegulatorViewInput, GetRegulatorViewOutput, GrantRegulatorViewInput, GrantRegulatorViewOutput, ListRegulatorViewsInput, ListRegulatorViewsOutput } from "../dto/regulator-view.dto";
export interface RegulatorViewRepository {
  listRegulatorViews(input: ListRegulatorViewsInput): Promise<ListRegulatorViewsOutput>;
  grantRegulatorView(input: GrantRegulatorViewInput): Promise<GrantRegulatorViewOutput>;
  getRegulatorView(input: GetRegulatorViewInput): Promise<GetRegulatorViewOutput>;
}

export type { GetRegulatorViewInput, GetRegulatorViewOutput, GrantRegulatorViewInput, GrantRegulatorViewOutput, ListRegulatorViewsInput, ListRegulatorViewsOutput } from "../dto/regulator-view.dto";
