/**
 * RevokeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevokeRepository Port
 *
 * DDD: Application port for revokerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RevokeRegulatorViewInput, RevokeRegulatorViewOutput } from "../dto/revoke.dto";
export interface RevokeRepository {
  revokeRegulatorView(input: RevokeRegulatorViewInput): Promise<RevokeRegulatorViewOutput>;
}

export type { RevokeRegulatorViewInput, RevokeRegulatorViewOutput } from "../dto/revoke.dto";
