/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve/index.js";
export * from "./consent/index.js";
export * from "./deny/index.js";
export * from "./owner-mediation-grant/index.js";
export * from "./processing-stop/index.js";
export * from "./withdraw/index.js";
