/**
 * RegulatorView DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: regulator-views
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RegulatorView DTOs
 *
 * DDD: Application DTOs for RegulatorView use cases.
 */

import type { GetRegulatorViewParams, GrantRegulatorViewRequestInput, ListRegulatorViewsParams } from "@consentrail/core/regulator-views/types";

export type ListRegulatorViewsInput = ListRegulatorViewsParams;

export type GrantRegulatorViewInput = GrantRegulatorViewRequestInput;

export type GetRegulatorViewInput = GetRegulatorViewParams;

export type ListRegulatorViewsOutput = {};

export type GrantRegulatorViewOutput = {};

export type GetRegulatorViewOutput = {};
