/**
 * ConsortiumRoles DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsortiumRoles Domain Module - Composition root
 *
 * DDD: Composition root for consortium-roles domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AttestRepositoryAdapter,
  ConsortiumRoleRepositoryAdapter,
  GoLiveGateRepositoryAdapter,
} from "@consentrail/adapters/consortium-roles";
import { getIdGeneratorService } from "@consentrail/adapters";
import type { AdapterDynamoDBClient } from "@consentrail/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAssignConsortiumRole,
  ExecuteAttestConsortiumRole,
  ExecuteGetConsortiumGoLiveGate,
  ExecuteGetConsortiumRole,
  ExecuteListConsortiumRoles,
} from "@consentrail/services/consortium-roles/usecases";
// Ports (interfaces)
import type {
  AttestRepository,
  ConsortiumRoleRepository,
  GoLiveGateRepository,
} from "@consentrail/services/consortium-roles/ports";

export interface ConsortiumRolesDomainModule {
  repos: {
    attests: AttestRepository;
    consortiumRoles: ConsortiumRoleRepository;
    goLiveGates: GoLiveGateRepository;
  };
  useCases: {
    attests: {
      get: ExecuteAttestConsortiumRole;
    };
    consortiumRoles: {
      create: ExecuteAssignConsortiumRole;
      get: ExecuteGetConsortiumRole;
      list: ExecuteListConsortiumRoles;
    };
    goLiveGates: {
      get: ExecuteGetConsortiumGoLiveGate;
    };
  };
}

export function buildConsortiumRolesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ConsortiumRolesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      attests?: AttestRepository;
      consortiumRoles?: ConsortiumRoleRepository;
      goLiveGates?: GoLiveGateRepository;
    } = {};

    obj.attests = new AttestRepositoryAdapter(dynamoClient);
    obj.consortiumRoles = new ConsortiumRoleRepositoryAdapter(dynamoClient);
    obj.goLiveGates = new GoLiveGateRepositoryAdapter(dynamoClient);
    return {
      attests: obj.attests!,
      consortiumRoles: obj.consortiumRoles!,
      goLiveGates: obj.goLiveGates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    attests: {
      get: new ExecuteAttestConsortiumRole(executionContext, idGenerator, repos.attests),
    },
    consortiumRoles: {
      create: new ExecuteAssignConsortiumRole(executionContext, idGenerator, repos.consortiumRoles),
      get: new ExecuteGetConsortiumRole(executionContext, idGenerator, repos.consortiumRoles),
      list: new ExecuteListConsortiumRoles(executionContext, idGenerator, repos.consortiumRoles),
    },
    goLiveGates: {
      get: new ExecuteGetConsortiumGoLiveGate(executionContext, idGenerator, repos.goLiveGates),
    },
  };
  return { repos, useCases: useCases as ConsortiumRolesDomainModule["useCases"] };
}
