/**
 * CreateDryRun DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triple-blind-exchange
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DryRunTripleBlindPolicyParams } from "@consentrail/core/triple-blind-exchange";

export function createCreateDryRunRequest(overrides: Partial<DryRunTripleBlindPolicyParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
