/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * SecurityEvents Domain Use Cases
 * 
 * List of all use case names for the security-events domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SECURITYEVENTS_USE_CASES = [
  "executeAcknowledgeSecurityEvent",
  "executeGetSecurityEvent",
  "executeListSecurityEvents",
  "executeRecordSecurityEvent"
] as const;
