/**
 * Handlers for OwnerMediationGrant
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConsentsDomainModule } from "../dependencies/consents-ddd.dependencies.js";
import type { GetOwnerMediationGrantInput, ListOwnerMediationGrantsInput, RequestOwnerMediationGrantInput } from "@consentrail/services/consents";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/owner-mediation-grants
 * Operation: listOwnerMediationGrants
 */
export async function listOwnerMediationGrants(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], consentId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ConsentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListOwnerMediationGrantsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.ownerMediationGrants.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/owner-mediation-grants
 * Operation: requestOwnerMediationGrant
 */
export async function requestOwnerMediationGrant(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ConsentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RequestOwnerMediationGrantInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.ownerMediationGrants.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/owner-mediation-grants/{grantId}
 * Operation: getOwnerMediationGrant
 */
export async function getOwnerMediationGrant(
  request: FastifyRequest<{ Params: { grantId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ConsentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetOwnerMediationGrantInput = {
    grantId: request.params.grantId,
  };
  const result = await deps.useCases.ownerMediationGrants.get.execute(input);
  return reply.code(200).send(result);
}


