/**
 * CreateHandToCounsel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rights
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { HandRightsCaseToCounselParams } from "@consentrail/core/rights";

export function createCreateHandToCounselRequest(overrides: Partial<HandRightsCaseToCounselParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
