/**
 * CounselGateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CounselGateRepository Port
 *
 * DDD: Application port for counselgaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCounselGateInput, GetCounselGateOutput, ListCounselGatesInput, ListCounselGatesOutput, OpenCounselGateInput, OpenCounselGateOutput } from "../dto/counsel-gate.dto";
export interface CounselGateRepository {
  listCounselGates(input: ListCounselGatesInput): Promise<ListCounselGatesOutput>;
  openCounselGate(input: OpenCounselGateInput): Promise<OpenCounselGateOutput>;
  getCounselGate(input: GetCounselGateInput): Promise<GetCounselGateOutput>;
}

export type { GetCounselGateInput, GetCounselGateOutput, ListCounselGatesInput, ListCounselGatesOutput, OpenCounselGateInput, OpenCounselGateOutput } from "../dto/counsel-gate.dto";
