/**
 * Repository interface for CounselGate
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: counsel-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CounselGateEntity
} from "../models/counsel-gate.entity.js";
import type {
  ListCounselGatesParams,
  CounselGate
} from "../types/index.js";
/**
 * CounselGateRepository Interface
 */
export interface CounselGateRepository extends CreateReadRepository<CounselGateEntity, CounselGate, string, ListCounselGatesParams> {

}
