/**
 * ConsortiumRoleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsortiumRoleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConsortiumRoleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConsortiumRoleRepository,
} from "@consentrail/services/consortium-roles";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConsortiumRoleRepositoryDdb } from "./consortium-role-repository.ddb.js";

/**
 * ConsortiumRoleRepositoryAdapter
 *
 * Implements ConsortiumRoleRepository port for infrastructure layer.
 */
export class ConsortiumRoleRepositoryAdapter implements ConsortiumRoleRepository {
  private readonly ddb: ConsortiumRoleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConsortiumRoleRepositoryDdb(this.dynamoClient);
  }

  async listConsortiumRoles(input: Parameters<ConsortiumRoleRepository['listConsortiumRoles']>[0]): Promise<Awaited<ReturnType<ConsortiumRoleRepository['listConsortiumRoles']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConsortiumRoles(input);
  }

  async assignConsortiumRole(input: Parameters<ConsortiumRoleRepository['assignConsortiumRole']>[0]): Promise<Awaited<ReturnType<ConsortiumRoleRepository['assignConsortiumRole']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.assignConsortiumRole(input);
  }

  async getConsortiumRole(input: Parameters<ConsortiumRoleRepository['getConsortiumRole']>[0]): Promise<Awaited<ReturnType<ConsortiumRoleRepository['getConsortiumRole']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getConsortiumRole(input);
  }
}
