/**
 * GoLiveGateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GoLiveGateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GoLiveGateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GoLiveGateRepository,
} from "@consentrail/services/consortium-roles";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GoLiveGateRepositoryDdb } from "./go-live-gate-repository.ddb.js";

/**
 * GoLiveGateRepositoryAdapter
 *
 * Implements GoLiveGateRepository port for infrastructure layer.
 */
export class GoLiveGateRepositoryAdapter implements GoLiveGateRepository {
  private readonly ddb: GoLiveGateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GoLiveGateRepositoryDdb(this.dynamoClient);
  }

  async getConsortiumGoLiveGate(input: Parameters<GoLiveGateRepository['getConsortiumGoLiveGate']>[0]): Promise<Awaited<ReturnType<GoLiveGateRepository['getConsortiumGoLiveGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getConsortiumGoLiveGate(input);
  }
}
