/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consortium-roles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./attest-repository.ddb.js";
export * from "./consortium-role-repository.ddb.js";
export * from "./go-live-gate-repository.ddb.js";
export * from "./attest-repository.adapter.js";
export * from "./consortium-role-repository.adapter.js";
export * from "./go-live-gate-repository.adapter.js";
